import React from "react";

const TermsOfUse = () => {
    return (

        <div class="container py-4">
            <div class="header-body text-center mb-7">
                <div class="justify-content-center row">
                    <h1 class="text-black">TERMS OF USE</h1>

                </div>
            </div>
            <div className="text-black text-justify">
                <h3> Last Updated On:_____</h3>
                <div class="  ml-4">
                    <p >
                         Thank you for using ZENYLOG. Our mission is to deepen the engagement and help the
                        Clients/Companies/Organizations by providing a revolutionary real time Attendance
                        management system to reinvent and ease the Day-to-day HR Management. We are helping
                        Clients/Companies/Organizations to power their Human Resource Management with Contactless
                        Attendance System. This includes Real Time Location, Geo Fenced, Office/Remote check-in for
                        the field employees, salary calculations including ESI, PF, PT deductions, payroll management,
                        leave management, time sheets, and much more on our ZENYLOG platform.
                    </p>
                    <p>
                        If this document is not in a language that you understand, you shall contact ZENYLOG at the
                        email maplebell.official@gmail.com. Failure to do so within 24 (Twenty-Four) hours from the time
                        of receipt of this document and your acceptance of this document shall be considered as your
                        understanding of this document.
                    </p>
                    <p>
                        This electronic record is generated by a computer system and does not require any physical or
                        digital signatures. By agreeing on the Terms &amp; Conditions of this electronic contract, you are
                        consenting to be bound by this User Agreement. Please ensure that you read and understand all
                        the provisions of this document before you start using the ZENYLOG.
                    </p>
                    <p>
                        If you do not agree or accept any of the Terms and Conditions contained herein, then please do
                        not use the ZENYLOG’s digital platform or avail any of the services being provided therein.
                    </p>
                </div>
                <div>

                    <h3> TERMS AND CONDITIONS</h3>
                    <div className="ml-4">

                        <p > Effective from: __, ___,2022</p>
                        <p>
                            Welcome to ZENYLOG.COM, This Website or App is owned and operated by MAPLEBELL
                            PRIVATE LIMITED, having its registered office at 363, 19th Main Road, Rajaji Nagar,
                            Bengaluru, Bengaluru Urban, Karnataka- 560010. By using our ZENYLOG services, you are
                            agreeing to be bound by our terms and conditions.
                        </p>
                        <p>
                            By visiting our Website and accessing the information and Services we provide, you understand
                            and agree to accept and adhere to the following terms and conditions as stated in this policy
                            (hereafter referred to as &#39;User Agreement&#39;), along with the terms and conditions as stated in our
                            Privacy Policy (please refer to the Privacy Policy link of this Website for more information).
                        </p>
                        <p>
                            We reserve the right to change this User Agreement from time to time without notice. You
                            acknowledge and agree that it is your responsibility to review this User Agreement periodically
                            to familiarize yourself with any modifications. Your continued use of this site and app after such
                        </p>
                        <p>
                            modifications will constitute acknowledgment and agreement of the modified terms and
                            conditions.
                        </p>

                        <h4>1. RESPONSIBLE USE AND CONDUCT:</h4>
                        <div className="ml-4">
                            <p>
                                1.1. In order to access our Services, you may be required to provide certain information about
                                yourself (such as identification, email, phone number, contact details, etc.) as part of the
                                registration process, or as part of your ability to use the Services available on the
                                ZENYLOG Website or App. You agree that any information you provide will always be
                                accurate, correct, and up to date.
                            </p>
                            <p>
                                1.2. You are responsible for maintaining the confidentiality of any login information
                                associated with any account you use to access our Services. Accordingly, you are
                                responsible for all activities that occur under your accounts.
                            </p>
                            <p>
                                1.3. Accessing (or attempting to access) any of our Services by any means other than through
                                the means we provide, is strictly prohibited. You specifically agree not to access (or
                                attempt to access) any of our Services through any automated, unethical or
                                unconventional means.
                            </p>
                            <p>
                                1.4. Engaging in any activity that disrupts or interferes with our Services, including the
                                servers and/or networks to which our Services are located or connected, is strictly
                                prohibited.
                            </p>
                            <p> 1.5. You are solely responsible any consequences, losses, or damages that we may directly or
                                indirectly incur or suffer due to any unauthorized activities conducted by you, as
                                explained above, and may incur criminal or civil liability.
                            </p>
                            <p>
                                1.6. We may provide various open communication tools on ZENYLOG, such as public chat,
                                forums, message boards, service ratings and reviews, various social media services, etc.
                                You understand that generally we do not pre-screen or monitor the content posted by
                                users of these various communication tools, which means that if you choose to use these
                                tools to submit any type of content to our ZENYLOG, then it is your personal
                                responsibility to use these tools in a responsible and ethical manner. By posting
                                information or otherwise using any open communication tools as mentioned, you agree
                                that you will not upload, post, share, or otherwise distribute any information that:
                                <ol type="a">
                                    <li>Is illegal, threatening, defamatory, abusive, harassing, degrading, intimidating,
                                        fraudulent, deceptive, invasive, racist, or contains any type of suggestive,
                                        inappropriate, or explicit language;</li>

                                    <li>Infringes on any trademark, patent, trade secret, copyright, or other proprietary rights</li>
                                    of any party;
                                    <li>Contains any type of unauthorized or unsolicited advertising;</li>
                                    <li> Impersonates any person or entity, including any ZENYLOG employees or
                                        representatives.</li>
                                </ol>
                            </p>

                            <p>
                                1.7. We have the right at our sole discretion to remove any information that, we feel in our
                                judgment does not comply with this User Agreement, along with any information that we
                                feel is otherwise offensive, harmful, objectionable, inaccurate, or violates any
                                ZENYLOG copyrights or trademarks. We are not responsible for any delay or failure in
                                removing such information. If you post information that we choose to remove, you
                                hereby consent to such removal, and consent to waive any claim against us.
                            </p>
                            <p>
                                1.8. We do not assume any liability for any information posted by you on ZENYLOG
                                Website or App. However, any information posted by you using any open
                                communication tools on our website and app, provided that it doesn&#39;t violate or infringe
                                on any ZENYLOG copyrights or trademarks, becomes the property of MAPLEBELL
                                PRIVATE LIMITED, and as such, gives us a perpetual, irrevocable, worldwide, royalty-
                                free, exclusive license to reproduce, modify, adapt, translate, publish, publicly display
                                and/or distribute as we see fit. This only refers and applies to the information posted via
                                open communication tools as described, and does not refer to information that is provided
                                as part of the registration process, necessary in order to use our Services. All information
                                provided as part of our registration process is covered by our Privacy Policy.</p>
                            <p>
                                1.9. You agree to indemnify and hold harmless ZENYLOG a digital property of
                                MAPLEBELL PRIVATE LIMITED, and their directors, officers, managers, employees,
                                Investors, agents, and licensors, from and against all losses, expenses, damages and costs,
                                including reasonable attorneys&#39; fees, resulting from any violation of this User Agreement
                                or the failure to fulfill any obligations relating to your account incurred by you or any
                                other person using your account. We reserve the right to take over the exclusive defense
                                of any claim for which we are entitled to indemnification under this User Agreement. In
                                such event, you shall provide us with such cooperation as is reasonably requested by us.
                            </p>
                        </div>

                        <h4> 2. ACCOUNT TERMS:</h4>
                        <div className="ml-4">
                            <p>
                                2.1. To access and use the Services of ZENYLOG, you must register on ZENYLOG.COM or
                                on its App (“Account”). To complete your Account registration, you must provide us
                                with your full legal name, business address, phone number, a valid email address, and
                                any other information indicated as required. ZENYLOG may reject your application for
                                an Account, or cancel an existing Account, for any reason, at our sole discretion.
                            </p>
                            <p>

                                2.2. “Age Restrictions”. You must be the older of: (i) 18 years, or (ii) at least the age of
                                majority in the jurisdiction where you reside and from which you use the Services to
                                open an Account.
                            </p>
                            <p>
                                2.3. You acknowledge that ZENYLOG will use the email address you provide on opening an
                                Account or as updated by you from time to time as the primary method for
                                communication with you (“Primary Email Address”). You must monitor the Primary
                                Email Address you provide to ZENYLOG and your Primary Email Address must be
                                capable of both sending and receiving messages. Your email communications with
                                ZENYLOG can only be authenticated if they come from your Primary Email Address.
                            </p>
                            <p>
                                2.4. You are responsible for keeping your password secure. ZENYLOG cannot and will not
                                be liable for any loss or damage from your failure to maintain the security of your
                                Account and password.
                            </p>
                            <p>
                                2.5. You agree not to work around, bypass, or circumvent any of the technical limitations of
                                the Services, use any tool to enable features or functionalities that are otherwise disabled
                                in the Services, or decompile, disassemble or otherwise reverse engineer the Services.
                            </p>
                        </div>

                        <h4>3. HOW DOES IT WORKS?</h4>
                        <div className="ml-4">
                            <p>
                                3.1. As a real time Attendance Management System, ZENYLOG works on contactless
                                attendance system with its prime motive to ease day-to-day HR management for the
                                Clients/Companies/Organizations. We use an innovative approach to provide effective,
                                result-oriented Services to our clients and this includes Real Time Location, Geo Fenced,
                                Office/Remote check-in for the field employees, salary calculations including ESI, PF,
                                PT deductions, payroll management, leave management, time sheets, and much more by
                                using through ZENYLOG App or Website.
                            </p>
                            <p>
                                3.2. Periodically, you (the “User”) may get customized experience and services on purchasing
                                our services, ZENYLOG is providing digital Human Resources Management System to
                                Clients/Companies/Organizations. ZENYLOG’s service portfolio includes
                                aforementioned services or other customized services accordingly to
                                Clients/Companies/Organizations requirements.
                            </p>
                            <p>
                                3.3. If you choose to opt a paid service on ZENYLOG, you will be charged a fee for availing
                                our paid services. This fee is intended in part to cover ZENYLOG’s technical
                                maintenance and other costs involved in operating the ZENYLOG’s App or Website.
                            </p>
                            <p>

                                3.4. Purchase made on the ZENYLOG Website or App must be for end consumption. You
                                must not use the Services or Customized Service purchased on the ZENYLOG for any
                                commercial, promotional, resale or further distribution purposes.
                            </p>
                        </div>
                        <h4>4. SERVICES BOOKING AND FINANCIAL TERMS:</h4>
                        <div className="ml-4">
                            <p>
                                4.1. The ZENYLOG App or Website allows users to order for a service or request for availing
                                the service, upon acceptance of such orders, requests, by the ZENYLOG, the
                                ZENYLOG, subject to the terms and conditions set out herein, facilitates delivery of
                                services, or completion of service request through the ZENYLOG Website, App or any
                                other relevant means.
                            </p>
                            <p>
                                4.2. ZENYLOG is an online service providing platform by engaging the
                                Clients/Companies/Organizations. We reserve the right to refuse the services on the
                                Website or App at our sole discretion to anyone for any reason at any time.
                            </p>
                            <p>
                                4.3. This Website and App does not screen or censor the Users who register on and access the
                                ZENYLOG platform. You assume all risks associated with dealing with other users with
                                whom you come in contact through the Website and App. You agree to use the
                                ZENYLOG only for the lawful purposes without infringing the rights or restricting the
                                use of this platform by and the third party.
                            </p>
                            <p>
                                4.4. All payments made against the Services available on the ZENYLOG by the Users shall
                                be compulsory in INR acceptable in the Republic of India. The ZENYLOG will not
                                facilitate transactions with respect to any other form of currency with respect to the
                                Services made on Website. You can pay by (i) credit card or debit card or net banking;
                                (ii) any other RBI approved payment method at the time of ordering a Service or
                                scheduling a Service; or (iii) credit or debit card or cash at the time of Service delivery.
                                You understand, accept and agree that the payment facility provided by ZENYLOG is
                                neither a banking nor financial service but is merely a facilitator providing an electronic,
                                automated online electronic payment, receiving payment on Service delivery and
                                remittance facility for the transactions on the ZENYLOG using the existing authorized
                                banking infrastructure and credit card payment gateway networks. Further, by providing
                                a payment facility, ZENYLOG is neither acting as trustees nor acting in a fiduciary
                                capacity with respect to the transaction or the transaction price.
                            </p>
                            <p>
                                4.5. When you register to order a Digital Services for the Management of Human Resources,
                                you agree to pay us the specific monetary amounts required to facilitates those Services.
                                The amount will be described to you during the booking of a Service or Order. The final
                                amount required for payment for availing the Services will be shown to you immediately
                                prior to the final booking of Services.
                            </p>
                            <p>

                                4.6. The prices reflected on the ZENYLOG, shall be determined by MAPLEBELL PRIVATE
                                LIMITED. Very rarely, prices may change at the time of placing an order or booking a
                                Service due to the market fluctuations, changing the Service price without due intimation
                                and such change of price are at the sole discretion of the ZENYLOG attributing to
                                various factors beyond control.
                            </p>
                            <p>
                                4.7. Certain services offered by the ZENYLOG may be eligible for business purchases, upon
                                your purchase of Service(s) eligible for business purchases, you may be able to avail the
                                benefits of the GST input tax credit. Accordingly, at your request, an invoice containing
                                the GSTIN as provided by you (“Tax Invoice”) shall be issued to you by the seller(s)
                                selling such services through ZENYLOG.
                            </p>
                        </div>

                        <h4>5. PRIVACY:</h4>
                        <div className="ml-4">
                            <p>
                                5.1. Through the use of ZENYLOG Website or App, you may provide us with certain
                                information. By using the ZENYLOG, you authorize the ZENYLOG to use your
                                information in India and any other country where the ZENYLOG may operate. We view
                                the protection of Your Privacy as very important principle. We understand clearly that
                                you and your personal information in one of our most important assets.
                            </p>
                            <p>
                                5.2. We store or process your information including any sensitive financial information
                                collected (as defined under the Information Technology Act, 2000), if any, on computers
                                that may be protected by physical as well as reasonable technological security measures
                                and procedures in accordance with Information Technology Act, 2000 and rules
                                thereunder.
                            </p>
                            <p>
                                5.3. Your privacy is very important to us, which is why we&#39;ve created a separate Privacy
                                Policy in order to explain in detail how we collect, manage, process, secure, and store
                                your private information. Our privacy policy is included under the scope of this User
                                Agreement. To read our privacy policy in its entirety, click on the Privacy Policy link.
                                5.4. We may disclose your personal information if required to do so by law or in the good
                                faith belief that such disclosure is reasonably necessary to respond to court orders, or
                                other legal processes. We may disclose personal Information to law enforcement
                                agencies, or others in the good faith belief that such disclosure is reasonably necessary to
                                enforce our Terms and Conditions or Privacy Policy.
                            </p>
                        </div>

                        <h4>6. LIMITATION OF WARRANTIES:</h4>
                        <div className="ml-4">

                            <p> By using ZENYLOG, you understand and agree that all Services we provide, and deliver are
                                &quot;Customizable&quot; and &quot;As Available&quot; on the Website or App. This means that we do not represent
                                or warrant to you that:
                            </p>
                            <ol type="a">
                                <li>
                                    ZENYLOG does not warrant that your use of Services will be always uninterrupted or
                                    error-free, that ZENYLOG will review the information and Services delivered through
                                    the Website or App in a timely manner for the accuracy or that it will preserve or
                                    maintain any such information or Services without loss.
                                </li>
                                <li>
                                    ZENYLOG shall not be liable for delays, interruptions, Service failure, or other problems
                                    inherent in use of the internet and electronic communications or other systems outside the
                                    reasonable control of ZENYLOG.
                                </li>
                            </ol>
                        </div>


                        <h4> 7. LIMITATION OF LIABILITY AND INDEMNIFICATION:</h4>
                        <div className="ml-4">
                            <p>
                                7.1. In conjunction with the Limitation of Warranties as explained above, you expressly
                                understand and agree that any claim against us shall be limited to the amount you paid, if
                                any, for use of our services. ZENYLOG will not be liable for any direct, indirect,
                                incidental, consequential or exemplary loss or damages which may be incurred by you as
                                a result of using our resources, or as a result of any changes, data loss or corruption,
                                cancellation, loss of access, or downtime to the full extent that applicable limitation of
                                liability laws apply.
                            </p>
                            <p>
                                7.2. You shall defend, indemnify and hold harmless ZENYLOG its owners, affiliates,
                                independent partners, and its respective officers, directors, agents, and employees
                                (“Indemnified Parties”), from and against any claim, damages, demand or actions
                                including attorney’s fees, made by any third party against the indemnified parties or
                                penalty imposed against the indemnified parties, due to arising out of your breach of this
                                Terms of Use, Privacy Policy and Other Policies or your violation of any law, rules or
                                regulations or the rights (including infringement of intellectual property rights) of a third
                                party.
                            </p>
                        </div>

                        <h4> 8. COPYRIGHTS / TRADEMARKS:</h4>
                        <div className="ml-4">
                            <p>
                                8.1. All content and materials available on ZENYLOG Website or App, including but not
                                limited to text, graphics, code, images and logos are the intellectual property of
                                MAPLEBELL PRIVATE LIMITED., and are protected by applicable copyright and
                                trademark law. Any inappropriate use, including but not limited to the reproduction,
                                distribution, display or transmission of any content on this Website is strictly prohibited,
                                unless specifically authorized by MAPLEBELL PRIVATE LIMITED.
                            </p>
                            <p>

                                8.2. You must not use any part of the materials on the ZENYLOG’s Website or App for
                                commercial purposes without obtaining a license to do so from us or our licensors. If you
                                print off, copy or download any part of the ZENYLOG in breach of these Terms of Use,
                                your right to use the Website will cease immediately and you must, at our option, return
                                or destroy any copies of the materials you have made.
                                8.3. In order to make the Services available to you, you hereby grant the ZENYLOG a
                                royalty-free, non-exclusive, worldwide license to copy, display, use, broadcast, transmit
                                and make derivate works of any information you upload or otherwise make available to
                                the Website or App. The ZENYLOG claims no further proprietary rights in your
                                information. If you feel that any of your Intellectual Property rights have been infringed
                                or otherwise violated by the posting of information or media by another of Our users,
                                please contact Us or write an email at: maplebell.official@gmail.com;
                            </p>
                        </div>

                        <h4>9. TERMINATION OF USE:</h4>
                        <div className="ml-4">
                            <p>
                                9.1. You agree that we may, at our sole discretion, suspend or terminate your access to all or
                                part of our Website, App and Services with or without notice and for any reason,
                                including, without limitation, breach of this User Agreement. Any suspected illegal,
                                fraudulent or abusive activity may be grounds for terminating your relationship and may
                                be referred to appropriate law enforcement authorities. Upon suspension or termination,
                                your right to use the services we provide on ZENYLOG will immediately cease, and we
                                reserve the right to remove or delete any information that you may have on file with us,
                                including any account or login information.
                            </p>
                            <p>
                                9.2. The ZENYLOG specifically reserves the right to terminate these Terms of Services if
                                You violate any of the terms outlined herein, including but not limited to, violating the
                                Intellectual Property rights of the MAPLEBELL PRIVATE LIMITED. or a third party,
                                failing to comply with the applicable laws or other legal obligations, and/or publishing or
                                distributing illegal material. If you have registered for an account with us, you may also
                                terminate these Terms of Services at any time by contacting us and requesting
                                termination. At the termination of these Terms of Services, any provisions that would be
                                expected to survive termination by their nature shall remain in full force and effect.
                            </p>
                        </div>

                        <h4> 10. GOVERNING LAW:</h4>
                        <div className="ml-4">
                            <p>
                                10.1. The ZENYLOG Website and App is a digital property of and controlled by
                                MAPLEBELL PRIVATE LIMITED from our office located in the state of Bengaluru,
                                Karnataka, India. ZENYLOG’s Website or App can be accessed by most country around
                                world. These terms and conditions shall be governed, interpreted, and construed in
                                accordance with the laws of India, without regards to conflict of law provisions and for
                                resolution of any dispute arising out of your use of services or in relation of these terms
                                and conditions.
                            </p>
                            <p>
                                10.2. Furthermore, any action to enforce this User Agreement shall be brought in the courts
                                located in Bengaluru, Karnataka, India. You hereby agree to personal jurisdiction by such
                                courts, and waive any jurisdictional, venue, or inconvenient forum objections to such
                                courts.
                            </p>
                        </div>

                        <h4>11. SPAM POLICY:</h4>
                        <p className="ml-4">
                            You are strictly prohibited from using the Website and App or any of the ZENYLOG’s Services
                            for illegal spam activities, including gathering email addresses and personal information from
                            others or sending any mass commercial emails.
                        </p>

                        <h4>12. THIRD-PARTY LINKS &amp; CONTENTS:</h4>
                        <p className="ml-4">

                            The ZENYLOG may occasionally post links of third-party websites or other services through
                            Google ad-sense on its Website. You agree that the ZENYLOG is not responsible or liable for
                            any loss or damage caused as a result of your clicking on the links of any third-party websites
                            available on our Website and App.
                        </p>

                        <h4>13. SHIPPING, CANCELLATION AND REFUND:</h4>
                        <div className="ml-4">
                            <p>
                                13.1. You agree to ensure payment for any services, you may order from the ZENYLOG’s
                                Website or App and you acknowledge and affirm that prices are subject to change. While
                                ordering any Services, you agree to provide us with a valid email and shipping address,
                                as well as valid billing information. We reserve the right to reject or cancel an order for
                                any reason, including errors or omissions in the information you provide to us. If we do
                                so after payment has been processed, we will issue a refund to you in the amount of the
                                Purchase price. We also may request additional information from you prior to confirming
                                a sale and we reserve the right to place any additional restrictions on the sale of any of
                                our Services.
                            </p>
                            <p>
                                13.2. You agree to ensure payment for any Customized Service you may purchase from us and
                                you acknowledge and affirm that prices are subject to change. For the sale of any
                                Customized Service, we may preauthorize your credit or debit card at the time you place
                                an order or we may simply charge your card upon shipment.
                            </p>
                            <p>

                                13.3. You agree to monitor your method of payment. Shipments costs and dates are subject to
                                change from the costs and dates you are quoted due to unforeseen circumstances. For any
                                questions, concerns, or disputes, you agree to contact us in a timely manner at the
                                following: maplebell.official@gmail.com
                            </p>
                        </div>

                        <h4>14. FEEDBACK AND REVIEWS:</h4>
                        <div className="ml-4">
                            <p>
                                14.1. ZENYLOG welcomes any ideas and/or suggestions regarding improvements or additions
                                to the Services. Under no circumstances will any disclosure of any idea, suggestion or
                                related material or any review of the Services (collectively, “Feedback&quot;) to ZENYLOG
                                be subject to any obligation of confidentiality or expectation of compensation. By
                                submitting Feedback to ZENYLOG (whether submitted directly to ZENYLOG or posted
                                on any ZENYLOG hosted forum or page), you waive any and all rights in the Feedback
                                and that ZENYLOG is free to implement and use the Feedback if desired, as provided by
                                you or as modified by ZENYLOG, without obtaining permission or license from you.
                                Any reviews of a Services that you submit to ZENYLOG must be accurate to the best of
                                your knowledge, and must not be illegal, obscene, threatening, defamatory, invasive of
                                privacy, infringing of intellectual property rights, or otherwise injurious to ZEENYLOG
                                or objectionable. ZENYLOG reserves the right (but not the obligation) to remove or edit
                                Feedback of any Services, but does not regularly inspect posted Feedback.
                            </p>
                            <p>
                                14.2. We welcome Users feedback but are under no obligation to ensure that ideas and
                                suggestions regarding ZENNYLOG Services, selling through ZENYLOG Website or
                                App remain confidential and we can use the feedback in any way we want.
                            </p>
                        </div>

                        <h4>15. MODIFICATIONS AND VARIATIONS:</h4>
                        <div className="ml-4">
                            <p>
                                15.1. We reserve the right, in our sole and absolute discretion, to update or change any portion
                                of the Terms of Service at any time. We will provide you with reasonable advance notice
                                of changes to the Terms of Service that materially adversely affect your use of the
                                Services or your rights under the Terms of Service by sending an email to the Primary
                                Email Address, providing notice through the ZENYLOG administrative console, or by
                                similar means. However, ZENYLOG may make changes that materially adversely affect
                                your use of the Services or your rights under the Terms of Service at any time and with
                                immediate effect (i) for legal, regulatory, fraud and abuse prevention, or security reasons;
                                or (ii) to restrict products or activities that we deem unsafe, inappropriate, or offensive.
                                Unless we indicate otherwise in our notice (if applicable), any changes to the Terms of
                                Service will be effective immediately upon posting of such updated terms at this location.
                                Your continued access to or use of the Services after we provide such notice, if

                                applicable, or after we post such updated terms, constitutes your acceptance of the
                                changes and consent to be bound by the Terms of Service as amended. If you do not
                                agree to the amended Terms of Service, you must stop accessing and using the Services.
                            </p>
                            <p>
                                15.2. ZENYLOG may change the Prices for the Services from time-to-time. We will provide
                                you with a notice prior to any changes in Fees by sending an email to the Primary Email
                                Account, providing notice through the ZENYLOG administrative console, or by similar
                                means. ZENYLOG will not be liable to you for any modification, price change,
                                suspension or discontinuance of the Services (or any part thereof).
                            </p>
                            <p>
                                15.3. If we make a change to the Terms of Service that adversely affects your rights under the
                                Terms of Service or your use of our Services in a material way, we will notify you in
                                advance (unless the change relates to legal requirements or to prevent abuse of our
                                Services, among other things).
                            </p>
                        </div>

                        <h4> 16. ENTIRE AGREEMENT:</h4>
                        <p className="ml-4">
                            These Terms and Conditions, Privacy Policy and any other terms or policies as may be
                            prescribed by ZENYLOG from time to time, constitute the entire agreement between you and the
                            ZENYLOG, which will govern your use of or access to the Services and/or the platform,
                            superseding any prior agreements between you and ZENYLOG regarding such use or access.
                        </p>

                        <h4>17. CONTACT INFORMATION:</h4>
                        <div className="ml-4">
                            <p >
                            If you have any questions or comments about ZENYLOG Terms of Service as outlined above,
                            </p>
                            <h4>
                            you can contact us at:
                            </h4>
                            <p className="mb-0">
                            ZENYLOG,
                            </p>
                            <p className="mb-0">
                            A digital property of MAPLEBELL PRIVATE LIMITED
                            </p>
                            <p className="mb-0">
                            363, 19th Main Road,
                            </p>
                            <p className="mb-0">
                            Rajaji Nagar, Bengaluru,
                            </p>
                            <p className="mb-0">
                            Bengaluru Urban, Karnataka- 560010.
                            </p>
                            <p className="mb-0">
                            Email Address: maplebell.official@gmail.com
                            </p>
                            <p className="mb-0">
                            Phone Number:  +91 93424 99299
                            </p>
                        </div>
                    </div>
                </div>
            </div >
        </div >
    )
}
export default TermsOfUse;