export const RESET_AUTH = 'RESET_AUTH'


export const VALIDATE_USER = 'VALIDATE_USER';
export const VALIDATE_USER_SUCCESS = 'VALIDATE_USER';
export const VALIDATE_USER_FAILURE = 'VALIDATE_USER';

export const VALIDATE_REGISTER_USER = 'VALIDATE_REGISTER_USER';
export const VALIDATE_REGISTER_USER_SUCCESS = 'VALIDATE_REGISTER_USER_SUCCESS';
export const VALIDATE_REGISTER_USER_FAILURE = 'VALIDATE_REGISTER_USER_FAILURE';

export const OTP_REGISTER = 'OTP_REGISTER';
export const OTP_REGISTER_SUCCESS = 'OTP_REGISTER_SUCCESS';
export const OTP_REGISTER_FAILURE = 'OTP_REGISTER_FAILURE';
export const GET_USER_BUSINESS_PLACES = 'GET_USER_BUSINESS_PLACES';
export const GET_USER_BUSINESS_PLACES_SUCCESS ='GET_USER_BUSINESS_PLACES_SUCCESS';
export const GET_USER_BUSINESS_PLACES_FAILURE ='GET_USER_BUSINESS_PLACES_FAILURE';
export const VALIDATE_USER_BUSINESS = 'VALIDATE_USER_BUSINESS';
export const VALIDATE_USER_BUSINESS_SUCCESS = 'VALIDATE_USER_BUSINESS_SUCCESS';
export const VALIDATE_USER_BUSINESS_FAILURE = 'VALIDATE_USER_BUSINESS_FAILURE';


export const REGISTER_ADMIN = 'REGISTER_ADMIN';
export const REGISTER_ADMIN_SUCCESS = 'REGISTER_ADMIN_SUCCESS';
export const REGISTER_ADMIN_FAILURE = 'REGISTER_ADMIN_FAILURE';


export const BRAND_SECTOR = 'BRAND_SECTOR';
export const BRAND_SECTOR_SUCCESS = 'BRAND_SECTOR_SUCCESS';
export const BRAND_SECTOR_FAILURE = 'BRAND_SECTOR_FAILURE';
export const BUSINESS_PLACES_DETAILS = 'BUSINESS_PLACES_DETAILS';
export const BUSINESS_PLACES_DETAILS_SUCCESS ='BUSINESS_PLACES_DETAILS_SUCCESS';
export const BUSINESS_PLACES_DETAILS_FAILURE ='BUSINESS_PLACES_DETAILS_FAILURE';
export const REGISTER_COMPANY = 'REGISTER_COMPANY';
export const REGISTER_COMPANY_SUCCESS = 'REGISTER_COMPANY_SUCCESS';
export const REGISTER_COMPANY_FAILURE = 'REGISTER_COMPANY_FAILURE';
export const SECTOR_SERVICE_TYPES = 'SECTOR_SERVICE_TYPES';
export const SECTOR_SERVICE_TYPES_SUCCESS = 'SECTOR_SERVICE_TYPES_SUCCESS';
export const SECTOR_SERVICE_TYPES_FAILURE = 'SECTOR_SERVICE_TYPES_FAILURE';
export const SELECT_BUSINESS_PLACE_ID = 'SELECT_BUSINESS_PLACE_ID';
export const SET_ALTERNATIVE_MOBILE_NUMBER = 'SET_ALTERNATIVE_MOBILE_NUMBER';
export const CLEAR_VALIDATE_USER_BUSINESS = 'CLEAR_VALIDATE_USER_BUSINESS';
export const RESET_SEARCHED_BUSINESS_PLACES = 'RESET_SEARCHED_BUSINESS_PLACES';
export const CLEAR_OTP_REGISTER = 'CLEAR_OTP_REGISTER';
export const CLEAR_VALIDATE_REGISTER_USER = 'CLEAR_VALIDATE_REGISTER_USER';
export const SET_REGISTER_MOBILE_NUMBER = 'SET_REGISTER_MOBILE_NUMBER';
export const SET_LANGUAGE = 'SET_LANGUAGE';



/**
 * OTP_LOGIN
 */

export const OTP_LOGIN = 'OTP_LOGIN';
export const OTP_LOGIN_SUCCESS = 'OTP_LOGIN_SUCCESS';
export const OTP_LOGIN_FAILURE = 'OTP_LOGIN_FAILURE';

/**
 * validate guest user
 */

export const VALIDATE_GUEST_USER = 'VALIDATE_GUEST_USER';
export const VALIDATE_GUEST_USER_SUCCESS = 'VALIDATE_GUEST_USER_SUCCESS';
export const VALIDATE_GUEST_USER_FAILURE = 'VALIDATE_GUEST_USER_FAILURE';

