export const URL_DELETE_USER = "URL_DELETE_USER";
export const URL_DELETE_USER_SUCCESS = "URL_DELETE_USER_SUCCESS";
export const URL_DELETE_USER_FAIL = "URL_DELETE_USER_FAIL";

export const EDIT_PROFILE_PICTURE = "EDIT_PROFILE_PICTURE";
export const EDIT_PROFILE_PICTURE_SUCCESS = "EDIT_PROFILE_PICTURE_USER_SUCCESS";
export const EDIT_PROFILE_PICTURE_FAIL = "EDIT_PROFILE_PICTURE_FAIL";

export const FETCH_DESIGNATION = "FETCH_DESIGNATION";
export const FETCH_DESIGNATION_SUCCESS = "FETCH_DESIGNATION_SUCCESS";
export const FETCH_DESIGNATION_FAILURE = "FETCH_DESIGNATION_FAILURE";

export const FETCH_DEPARTMENT = "FETCH_DEPARTMENT";
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_FAILURE = "FETCH_DEPARTMENT_FAILURE";

export const FETCH_ALL_BRANCHES_LIST = "FETCH_ALL_BRANCHES_LIST";
export const FETCH_ALL_BRANCHES_LIST_SUCCESS =
  "FETCH_ALL_BRANCHES_LIST_SUCCESS";
export const FETCH_ALL_BRANCHES_LIST_FAILURE =
  "FETCH_ALL_BRANCHES_LIST_FAILURE";

export const FETCH_EMPLOYEE_DETAILS = "FETCH_EMPLOYEE_DETAILS";
export const FETCH_EMPLOYEE_DETAILS_SUCCESS = "FETCH_EMPLOYEE_DETAILS_SUCCESS";
export const FETCH_EMPLOYEE_DETAILS_FAILURE = "FETCH_EMPLOYEE_DETAILS_FAILURE";

export const FETCH_EMPLOYEE_LIST = "FETCH_EMPLOYEE_LIST";
export const FETCH_EMPLOYEE_LIST_SUCCESS = "FETCH_EMPLOYEE_LIST_SUCCESS";
export const FETCH_EMPLOYEE_LIST_FAILURE = "FETCH_EMPLOYEE_LIST_FAILURE";

export const POST_EMPLOYEE_ADDITION = "POST_EMPLOYEE_ADDITION";
export const POST_EMPLOYEE_ADDITION_SUCCESS = "POST_EMPLOYEE_ADDITION_SUCCESS";
export const POST_EMPLOYEE_ADDITION_FAILURE = "POST_EMPLOYEE_ADDITION_FAILURE";

export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";

export const FETCH_EMPLOYEE_TIME_SHEETS = "FETCH_EMPLOYEE_TIME_SHEETS";
export const FETCH_EMPLOYEE_TIME_SHEETS_SUCCESS =
  "FETCH_EMPLOYEE_TIME_SHEETS_SUCCESS";
export const FETCH_EMPLOYEE_TIME_SHEETS_FAILURE =
  "FETCH_EMPLOYEE_TIME_SHEETS_FAILURE";

export const FETCH_EMPLOYEE_CHECK_IN_LOGS = "FETCH_EMPLOYEE_CHECK_IN_LOGS";
export const FETCH_EMPLOYEE_CHECK_IN_LOGS_SUCCESS =
  "FETCH_EMPLOYEE_CHECK_IN_LOGS_SUCCESS";
export const FETCH_EMPLOYEE_CHECK_IN_LOGS_FAILURE =
  "FETCH_EMPLOYEE_CHECK_IN_LOGS_FAILURE";

export const FETCH_CHECK_IN_DETAILED_LOG_PER_DAY =
  "FETCH_CHECK_IN_DETAILED_LOG_PER_DAY";
export const FETCH_CHECK_IN_DETAILED_LOG_PER_DAY_SUCCESS =
  "FETCH_CHECK_IN_DETAILED_LOG_PER_DAY_SUCCESS";
export const FETCH_CHECK_IN_DETAILED_LOG_PER_DAY_FAILURE =
  "FETCH_CHECK_IN_DETAILED_LOG_PER_DAY_FAILURE";

export const FETCH_EMPLOYEE_EACH_USER_TIME_SHEETS =
  "FETCH_EMPLOYEE_EACH_USER_TIME_SHEETS";
export const FETCH_EMPLOYEE_EACH_USER_TIME_SHEETS_SUCCESS =
  "FETCH_EMPLOYEE_EACH_USER_TIME_SHEETS_SUCCESS";
export const FETCH_EMPLOYEE_EACH_USER_TIME_SHEETS_FAILURE =
  "FETCH_EMPLOYEE_EACH_USER_TIME_SHEETS_FAILURE";

export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";

export const ADD_DESIGNATION = "ADD_DESIGNATION";
export const ADD_DESIGNATION_SUCCESS = "ADD_DESIGNATION_SUCCESS";
export const ADD_DESIGNATION_FAILURE = "ADD_DESIGNATION_FAILURE";

export const ADD_FENCE_ADMIN = "ADD_FENCE_ADMIN";
export const ADD_FENCE_ADMIN_SUCCESS = "ADD_FENCE_ADMIN_SUCCESS";
export const ADD_FENCE_ADMIN_FAILURE = "ADD_FENCE_ADMIN_FAILURE";

export const FETCH_EMPLOYEE_ATTENDANCE_STATS =
  "FETCH_EMPLOYEE_ATTENDANCE_STATS";
export const FETCH_EMPLOYEE_ATTENDANCE_STATS_SUCCESS =
  "FETCH_EMPLOYEE_ATTENDANCE_STATS_SUCCESS";
export const FETCH_EMPLOYEE_ATTENDANCE_STATS_FAILURE =
  "FETCH_EMPLOYEE_ATTENDANCE_STATS_FAILURE";

export const FETCH_EMPLOYEE_TODAY_STATUS = "FETCH_EMPLOYEE_TODAY_STATUS";
export const FETCH_EMPLOYEE_TODAY_STATUS_SUCCESS =
  "FETCH_EMPLOYEE_TODAY_STATUS_SUCCESS";
export const FETCH_EMPLOYEE_TODAY_STATUS_FAILURE =
  "FETCH_EMPLOYEE_TODAY_STATUS_FAILURE";

export const FETCH_DOWNLOAD_TODAY_STATUS = "FETCH_DOWNLOAD_TODAY_STATUS";
export const FETCH_DOWNLOAD_TODAY_STATUS_SUCCESS =
  "FETCH_DOWNLOAD_TODAY_STATUS_SUCCESS";
export const FETCH_DOWNLOAD_TODAY_STATUS_FAILURE =
  "FETCH_DOWNLOAD_TODAY_STATUS_FAILURE";

export const FETCH_CHECK_IN_DETAILED_LOG = "FETCH_CHECK_IN_DETAILED_LOG";
export const FETCH_CHECK_IN_DETAILED_LOG_SUCCESS =
  "FETCH_CHECK_IN_DETAILED_LOG_SUCCESS";
export const FETCH_CHECK_IN_DETAILED_LOG_FAILURE =
  "FETCH_CHECK_IN_DETAILED_LOG_FAILURE";

export const SELECTED_CARD_TYPE = "SELECTED_CARD_TYPE";

export const SELECTED_DEPARTMENT_NAME = "SELECTED_DEPARTMENT_NAME";

export const SELECTED_DEPARTMENT_ID = "SELECTED_DEPARTMENT_ID";

export const SELECTED_EMPLOYEE_ID = "SELECTED_EMPLOYEE_ID";
export const SELECTED_EVENT_ID = "SELECTED_EVENT_ID";



export const FETCH_ATTENDANCE_CONSOLIDATED_CARDS =
  "FETCH_ATTENDANCE_CONSOLIDATED_CARDS";
export const FETCH_ATTENDANCE_CONSOLIDATED_CARDS_SUCCESS =
  "FETCH_ATTENDANCE_CONSOLIDATED_CARDS_SUCCESS";
export const FETCH_ATTENDANCE_CONSOLIDATED_CARDS_FAILURE =
  "FETCH_ATTENDANCE_CONSOLIDATED_CARDS_FAILURE";

export const UPDATE_EMPLOYEE_STATUS = "UPDATE_EMPLOYEE_STATUS";
export const UPDATE_EMPLOYEE_STATUS_SUCCESS = "UPDATE_EMPLOYEE_STATUS_SUCCESS";
export const UPDATE_EMPLOYEE_STATUS_FAILURE = "UPDATE_EMPLOYEE_STATUS_FAILURE";

export const RESET_REDUCER = "RESET_REDUCER";

export const FETCH_LEAVE_TYPES = "FETCH_LEAVE_TYPES";
export const FETCH_LEAVE_TYPES_SUCCESS = "FETCH_LEAVE_TYPES_SUCCESS";
export const FETCH_LEAVE_TYPES_FAILURE = "FETCH_LEAVE_TYPES_FAILURE";

export const APPLY_LEAVE = "APPLY_LEAVE";
export const APPLY_LEAVE_SUCCESS = "APPLY_LEAVE_SUCCESS";
export const APPLY_LEAVE_FAILURE = "APPLY_LEAVE_FAILURE";


export const ADD_LEAVE_FROM_DATE = "ADD_LEAVE_FROM_DATE";

export const FETCH_CALENDAR_DETAILS = "FETCH_CALENDAR_DETAILS";
export const FETCH_CALENDAR_DETAILS_SUCCESS = "FETCH_CALENDAR_DETAILS_SUCCESS";
export const FETCH_CALENDAR_DETAILS_FAILURE = "FETCH_CALENDAR_DETAILS_FAILURE";



export const CHANGE_EMPLOYEE_LEAVE_STATUS = "CHANGE_EMPLOYEE_LEAVE_STATUS";
export const CHANGE_EMPLOYEE_LEAVE_STATUS_SUCCESS =
  "CHANGE_EMPLOYEE_LEAVE_STATUS_SUCCESS";
export const CHANGE_EMPLOYEE_LEAVE_STATUS_FAILURE =
  "CHANGE_EMPLOYEE_LEAVE_STATUS_FAILURE";

export const ADD_HOLIDAY = "ADD_HOLIDAY";
export const ADD_HOLIDAY_SUCCESS = "ADD_HOLIDAY_SUCCESS";
export const ADD_HOLIDAY_FAILURE = "ADD_HOLIDAY_FAILURE";


export const DELETE_HOLIDAY = "DELETE_HOLIDAY";
export const DELETE_HOLIDAY_SUCCESS = "DELETE_HOLIDAY_SUCCESS";
export const DELETE_HOLIDAY_FAILURE = "DELETE_HOLIDAY_FAILURE";


export const GET_LEAVES_BY_TYPES = "GET_LEAVES_BY_TYPES"
export const GET_LEAVES_BY_TYPES_SUCCESS = "GET_LEAVES_BY_TYPES_SUCCESS";
export const GET_LEAVES_BY_TYPES_FAILURE = "GET_LEAVES_BY_TYPES_FAILURE";

export const GET_EMPLOYEES_LEAVES = "GET_EMPLOYEES_LEAVES"
export const GET_EMPLOYEES_LEAVE_SUCCESS = "GET_EMPLOYEES_LEAVE_SUCCESS";
export const GET_EMPLOYEES_LEAVES_FAILURE = "GET_EMPLOYEES_LEAVES_FAILURE";

export const GET_MODIFY_LOGS = "GET_MODIFY_LOGS"
export const GET_MODIFY_LOGS_SUCCESS = "GET_MODIFY_LOGS_SUCCESS";
export const GET_MODIFY_LOGS_FAILURE = "GET_MODIFY_LOGS_FAILURE";


export const GET_MIS_REPORT = "GET_MIS_REPORT"
export const GET_MIS_REPORT_SUCCESS = "GET_MIS_REPORT_SUCCESS";
export const GET_MIS_REPORT_FAILURE = "GET_MIS_REPORT_FAILURE";

export const RESET_MIS_REPORT_DATA = "RESET_MIS_REPORT_DATA"


export const GET_MIS_REPORT_DOWNLOAD = "GET_MIS_REPORT_DOWNLOAD"
export const GET_MIS_REPORT_DOWNLOAD_SUCCESS = "GET_MIS_REPORT_DOWNLOAD_SUCCESS";
export const GET_MIS_REPORT_DOWNLOAD_FAILURE = "GET_MIS_REPORT_DOWNLOAD_FAILURE";

export const GET_MIS_REPORT_CLEAR = "GET_MIS_REPORT_CLEAR"

export const GET_EMPLOYEE_DOCUMENT = "GET_EMPLOYEE_DOCUMENT";
export const GET_EMPLOYEE_DOCUMENT_SUCCESS = "GET_EMPLOYEE_DOCUMENT_SUCCESS";
export const GET_EMPLOYEE_DOCUMENT_FAILURE = "GET_EMPLOYEE_DOCUMENT_FAILURE";




export const ATTACH_USER_DOCUMENT = "ATTACH_USER_DOCUMENT";
export const ATTACH_USER_DOCUMENT_SUCCESS = "ATTACH_USER_DOCUMENT_SUCCESS";
export const ATTACH_USER_DOCUMENT_FAILURE = "ATTACH_USER_DOCUMENT_FAILURE";

/**
 * Admin My Branches
 */

export const GET_ADMIN_BRANCHES = "GET_ADMIN_BRANCHES";
export const GET_ADMIN_BRANCHES_SUCCESS = "GET_ADMIN_BRANCHES_SUCCESS";
export const GET_ADMIN_BRANCHES_FAILURE = "GET_ADMIN_BRANCHES_FAILURE";


export const POST_UPDATED_ADMIN_BRANCHES = "POST_UPDATED_ADMIN_BRANCHES";
export const POST_UPDATED_ADMIN_BRANCHES_SUCCESS = "POST_UPDATED_ADMIN_BRANCHES_SUCCESS";
export const POST_UPDATED_ADMIN_BRANCHES_FAILURE = "POST_UPDATED_ADMIN_BRANCHES_FAILURE";


export const IS_RENDER_ADMIN_BRANCHES = 'IS_RENDER_ADMIN_BRANCHES'


export const GET_BRANCHES_ADMIN = "GET_BRANCHES_ADMIN";
export const GET_BRANCHES_ADMIN_SUCCESS = "GET_BRANCHES_ADMIN_SUCCESS";
export const GET_BRANCHES_ADMIN_FAILURE = "GET_BRANCHES_ADMIN_FAILURE";

export const GET_FILTERED_BRANCHES = "GET_FILTERED_BRANCHES";

export const GET_LEAVES_TYPE_DETAILS = "GET_LEAVES_TYPE_DETAILS";


export const GET_EDIT_LEAVES_DETAILS = "GET_EDIT_LEAVES_DETAILS";



export const UPDATE_LEAVE_TYPE_DETAILS = "UPDATE_LEAVE_TYPE_DETAILS";
export const UPDATE_LEAVE_TYPE_DETAILS_SUCCESS = "UPDATE_LEAVE_TYPE_DETAILS_SUCCESS";
export const UPDATE_LEAVE_TYPE_DETAILS_FAILURE = "UPDATE_LEAVE_TYPE_DETAILS_FAILURE";


export const CURRENT_LEAVE_TYPE = "CURRENT_LEAVE_TYPE"



export const GET_EMPLOYEE_CHECK_IN_LOGS_REPORT = "GET_EMPLOYEE_CHECK_IN_LOGS_REPORT";
export const GET_EMPLOYEE_CHECK_IN_LOGS_REPORT_SUCCESS = "GET_EMPLOYEE_CHECK_IN_LOGS_REPORT_SUCCESS";
export const GET_EMPLOYEE_CHECK_IN_LOGS_REPORT_FAILURE = "GET_EMPLOYEE_CHECK_IN_LOGS_REPORT_FAILURE";



//enableFieldCheckIn
export const ENABLE_FIELD_CHECK_IN = "ENABLE_FIELD_CHECK_IN";
export const ENABLE_FIELD_CHECK_IN_SUCCESS = "ENABLE_FIELD_CHECK_IN_SUCCESS";
export const ENABLE_FIELD_CHECK_IN_FAILURE = "ENABLE_FIELD_CHECK_IN_FAILURE";

//enableOfficeCheckIn
export const ENABLE_OFFICE_CHECK_IN = "ENABLE_OFFICE_CHECK_IN";
export const ENABLE_OFFICE_CHECK_IN_SUCCESS = "ENABLE_OFFICE_CHECK_IN_SUCCESS";
export const ENABLE_OFFICE_CHECK_IN_FAILURE = "ENABLE_OFFICE_CHECK_IN_FAILURE";


//changeAttendanceSettings 
export const POST_FACE_VALIDATION_STATUS = "POST_FACE_VALIDATION_STATUS";
export const POST_FACE_VALIDATION_STATUS_SUCCESS = "POST_FACE_VALIDATION_STATUS_SUCCESS";
export const POST_FACE_VALIDATION_STATUS_FAILURE = "POST_FACE_VALIDATION_STATUS_FAILURE";

//get employee basic info

export const FETCH_EMPLOYEE_BASIC_INFO = "FETCH_EMPLOYEE_BASIC_INFO";
export const FETCH_EMPLOYEE_BASIC_INFO_SUCCESS = "FETCH_EMPLOYEE_BASIC_INFO_SUCCESS";
export const FETCH_EMPLOYEE_BASIC_INFO_FAILURE = "FETCH_EMPLOYEE_BASIC_INFO_FAILURE";

//get employee basic info

export const FETCH_EMPLOYEE_ATTENDANCE_INFO = "FETCH_EMPLOYEE_ATTENDANCE_INFO";
export const FETCH_EMPLOYEE_ATTENDANCE_INFO_SUCCESS = "FETCH_EMPLOYEE_ATTENDANCE_INFO_SUCCESS";
export const FETCH_EMPLOYEE_ATTENDANCE_INFO_FAILURE = "FETCH_EMPLOYEE_ATTENDANCE_INFO_FAILURE";

//Employee View details api handler

export const EMPLOYEE_VIEW_DETAILS_API_HANDLER = "EMPLOYEE_VIEW_DETAILS_API_HANDLER"

//  modify log for employee
export const EMPLOYEE_MODIFY_REQUEST = "EMPLOYEE_MODIFY_REQUEST";
export const EMPLOYEE_MODIFY_REQUEST_SUCCESS = "EMPLOYEE_MODIFY_REQUEST_SUCCESS";
export const EMPLOYEE_MODIFY_REQUEST_FAILURE = "EMPLOYEE_MODIFY_REQUEST_FAILURE";


// api for modify admin

export const ADMIN_MODIFY_LOG = "ADMIN_MODIFY_LOG";
export const ADMIN_MODIFY_LOG_SUCCESS = "ADMIN_MODIFY_LOG_SUCCESS";
export const ADMIN_MODIFY_LOG_FAILURE = "ADMIN_MODIFY_LOG_FAILURE";


//  change status of modify log request

export const CHANGE_MODIFY_LOG_STATUS = "CHANGE_MODIFY_LOG_STATUS";
export const CHANGE_MODIFY_LOG_STATUS_SUCCESS = "CHANGE_MODIFY_LOG_STATUS_SUCCESS";
export const CHANGE_MODIFY_LOG_STATUS_FAILURE = "CHANGE_MODIFY_LOG_STATUS_FAILURE";

// getCompanyBaseWeeklyCalendar

export const COMPANY_BASE_WEEKLY_CALENDAR = "COMPANY_BASE_WEEKLY_CALENDAR";
export const COMPANY_BASE_WEEKLY_CALENDAR_SUCCESS = "COMPANY_BASE_WEEKLY_CALENDAR_SUCCESS";
export const COMPANY_BASE_WEEKLY_CALENDAR_FAILURE = "COMPANY_BASE_WEEKLY_CALENDAR_FAILURE";


// setCompanyBaseWeeklyCalendar

export const SET_COMPANY_BASE_WEEKLY_CALENDAR = "SET_COMPANY_BASE_WEEKLY_CALENDAR";
export const SET_COMPANY_BASE_WEEKLY_CALENDAR_SUCCESS = "SET_COMPANY_BASE_WEEKLY_CALENDAR_SUCCESS";
export const SET_COMPANY_BASE_WEEKLY_CALENDAR_FAILURE = "SET_COMPANY_BASE_WEEKLY_CALENDAR_FAILURE";

//branchWiseEmployeesLeaves

export const GET_EMPLOYEE_BRANCH_WISE_LEAVES = "GET_EMPLOYEE_BRANCH_WISE_LEAVES";
export const GET_EMPLOYEE_BRANCH_WISE_LEAVES_SUCCESS = "GET_EMPLOYEE_BRANCH_WISE_LEAVES_SUCCESS";
export const GET_EMPLOYEE_BRANCH_WISE_LEAVES_FAILURE = "GET_EMPLOYEE_BRANCH_WISE_LEAVES_FAILURE";


//set employee leave history

export const GET_EMPLOYEE_LEAVE_HISTORY = 'GET_EMPLOYEE_LEAVE_HISTORY'

// getEmployeeLeaveTypes

export const GET_EMPLOYEE_LEAVE_TYPES = "GET_EMPLOYEE_LEAVE_TYPES";
export const GET_EMPLOYEE_LEAVE_TYPES_SUCCESS = "GET_EMPLOYEE_LEAVE_TYPES_SUCCESS";
export const GET_EMPLOYEE_LEAVE_TYPES_FAILURE = "GET_EMPLOYEE_LEAVE_TYPES_FAILURE";

// updateEmployeeAllocatedDays

export const UPDATE_EMPLOYEE_ALLOCATED_DAYS = "UPDATE_EMPLOYEE_ALLOCATED_DAYS";
export const UPDATE_EMPLOYEE_ALLOCATED_DAYS_SUCCESS = "UPDATE_EMPLOYEE_ALLOCATED_DAYS_SUCCESS";
export const UPDATE_EMPLOYEE_ALLOCATED_DAYS_FAILURE = "UPDATE_EMPLOYEE_ALLOCATED_DAYS_FAILURE";

// syncData

export const FETCH_SYNC_DATA = "FETCH_SYNC_DATA";
export const FETCH_SYNC_DATA_SUCCESS = "FETCH_SYNC_DATA_SUCCESS";
export const FETCH_SYNC_DATA_FAILURE = "FETCH_SYNC_DATA_FAILURE";

// UPDATE_COMPANY_GENERIC_SHIFT

export const UPDATE_COMPANY_GENERIC_SHIFT = "UPDATE_COMPANY_GENERIC_SHIFT";
export const UPDATE_COMPANY_GENERIC_SHIFT_SUCCESS = "UPDATE_COMPANY_GENERIC_SHIFT_SUCCESS";
export const UPDATE_COMPANY_GENERIC_SHIFT_FAILURE = "UPDATE_COMPANY_GENERIC_SHIFT_FAILURE";


// add Devices

export const ADD_ESSL_DEVICE = "ADD_ESSL_DEVICE";
export const ADD_ESSL_DEVICE_SUCCESS = "ADD_ESSL_DEVICE_SUCCESS";
export const ADD_ESSL_DEVICE_FAILURE = "ADD_ESSL_DEVICE_FAILURE";

// get Devices

export const GET_ESSL_DEVICE = "GET_ESSL_DEVICE";
export const GET_ESSL_DEVICE_SUCCESS = "GET_ESSL_DEVICE_SUCCESS";
export const GET_ESSL_DEVICE_FAILURE = "GET_ESSL_DEVICE_FAILURE";

// remove Devices

export const REMOVE_ESSL_DEVICE = "REMOVE_ESSL_DEVICE";
export const REMOVE_ESSL_DEVICE_SUCCESS = "REMOVE_ESSL_DEVICE_SUCCESS";
export const REMOVE_ESSL_DEVICE_FAILURE = "REMOVE_ESSL_DEVICE_FAILURE";

// updateEmployeesDeviceDetail

export const UPDATE_EMPLOYEE_DEVICE_DETAILS = "UPDATE_EMPLOYEE_DEVICE_DETAILS";
export const UPDATE_EMPLOYEE_DEVICE_DETAILS_SUCCESS = "UPDATE_EMPLOYEE_DEVICE_DETAILS_SUCCESS";
export const UPDATE_EMPLOYEE_DEVICE_DETAILS_FAILURE = "UPDATE_EMPLOYEE_DEVICE_DETAILS_FAILURE";

// getEmployeesDeviceDetail

export const GET_EMPLOYEE_DEVICE_DETAILS = "GET_EMPLOYEE_DEVICE_DETAILS";
export const GET_EMPLOYEE_DEVICE_DETAILS_SUCCESS = "GET_EMPLOYEE_DEVICE_DETAILS_SUCCESS";
export const GET_EMPLOYEE_DEVICE_DETAILS_FAILURE = "GET_EMPLOYEE_DEVICE_DETAILS_FAILURE";

//GET VENDERS

export const GET_VENDERS = "GET_VENDERS"
export const GET_VENDERS_SUCCESS = "GET_VENDERS_SUCCESS"
export const GET_VENDERS_FAILURE = "GET_VENDERS_FAILURE"


export const ADD_VENDERS = "ADD_VENDERS"
export const ADD_VENDERS_SUCCESS = "ADD_VENDERS_SUCCESS"
export const ADD_VENDERS_FAILURE = "ADD_VENDERS_FAILURE"

