export const POST_ADD_WEEKLY_SHIFT = "POST_ADD_WEEKLY_SHIFT";
export const POST_ADD_WEEKLY_SHIFT_SUCCESS = "POST_ADD_WEEKLY_SHIFT_SUCCESS";
export const POST_ADD_WEEKLY_SHIFT_FAILURE = "POST_ADD_WEEKLY_SHIFT_FAILURE";

export const FETCH_BRANCH_SHIFTS = "FETCH_BRANCH_SHIFTS";
export const FETCH_BRANCH_SHIFTS_SUCCESS = "FETCH_BRANCH_SHIFTS_SUCCESS";
export const FETCH_BRANCH_SHIFTS_FAILURE = "FETCH_BRANCH_SHIFTS_FAILURE";

export const FETCH_BRANCH_WEEKLY_SHIFTS = "FETCH_BRANCH_WEEKLY_SHIFTS";
export const FETCH_BRANCH_WEEKLY_SHIFTS_SUCCESS = "FETCH_BRANCH_WEEKLY_SHIFTS_SUCCESS";
export const FETCH_BRANCH_WEEKLY_SHIFTS_FAILURE = "FETCH_BRANCH_WEEKLY_SHIFTS_FAILURE";

export const SELECTED_BRANCH_SHIFT_GROUP_DETAILS = "SELECTED_BRANCH_SHIFT_GROUP_DETAILS"

export const POST_ADD_SHIFT = "POST_ADD_SHIFT";
export const POST_ADD_SHIFT_SUCCESS = "POST_ADD_SHIFT_SUCCESS";
export const POST_ADD_SHIFT_FAILURE = "POST_ADD_SHIFT_FAILURE";

export const SELECTED_WEEKLY_SHIFT_ID = "SELECTED_WEEKLY_SHIFT_ID";

export const SELECTED_WEEKLY_SHIFT_NAME = "SELECTED_WEEKLY_SHIFT_NAME";

export const FETCH_WEEKLY_SHIFT_DETAILS = "FETCH_WEEKLY_SHIFT_DETAILS";
export const FETCH_WEEKLY_SHIFT_DETAILS_SUCCESS = "FETCH_WEEKLY_SHIFT_DETAILS_SUCCESS";
export const FETCH_WEEKLY_SHIFT_DETAILS_FAILURE = "FETCH_WEEKLY_SHIFT_DETAILS_FAILURE";

export const FETCH_SHIFT_EMPLOYEES = "FETCH_SHIFT_EMPLOYEES";
export const FETCH_SHIFT_EMPLOYEES_SUCCESS = "FETCH_SHIFT_EMPLOYEES_SUCCESS";
export const FETCH_SHIFT_EMPLOYEES_FAILURE = "FETCH_SHIFT_EMPLOYEES_FAILURE";


export const FETCH_MY_SHIFTS = "FETCH_MY_SHIFTS";
export const FETCH_MY_SHIFTS_SUCCESS = "FETCH_MY_SHIFTS_SUCCESS";
export const FETCH_MY_SHIFTS_FAILURE = "FETCH_MY_SHIFTS_FAILURE";

export const RESET_REDUCER = "RESET_REDUCER";


export const GET_EMPLOYEE_WITH_SHIFTS = "GET_EMPLOYEE_WITH_SHIFTS";
export const GET_EMPLOYEE_WITH_SHIFTS_SUCCESS = "GET_EMPLOYEE_WITH_SHIFTS_SUCCESS";
export const GET_EMPLOYEE_WITH_SHIFTS_FAILURE = "GET_EMPLOYEE_WITH_SHIFTS_FAILURE";


export const POST_EMPLOYEE_SHIFT_CHANGE = "POST_EMPLOYEE_SHIFT_CHANGE";
export const POST_EMPLOYEE_SHIFT_CHANGE_SUCCESS = "POST_EMPLOYEE_SHIFT_CHANGE_SUCCESS";
export const POST_EMPLOYEE_SHIFT_CHANGE_FAILURE = "POST_EMPLOYEE_SHIFT_CHANGE_FAILURE";


export const GET_SHIFT_REQUESTED_EMPLOYEES = "GET_SHIFT_REQUESTED_EMPLOYEES";
export const GET_SHIFT_REQUESTED_EMPLOYEES_SUCCESS = "GET_SHIFT_REQUESTED_EMPLOYEES_SUCCESS";
export const GET_SHIFT_REQUESTED_EMPLOYEES_FAILURE = "GET_SHIFT_REQUESTED_EMPLOYEES_FAILURE";



export const GET_SHIFT_REQUESTED_STATUS = "GET_SHIFT_REQUESTED_STATUS";
export const GET_SHIFT_REQUESTED_STATUS_SUCCESS = "GET_SHIFT_REQUESTED_STATUS_SUCCESS";
export const GET_SHIFT_REQUESTED_STATUS_FAILURE = "GET_SHIFT_REQUESTED_STATUS_FAILURE";



export const POST_REQUEST_SHIFT_CHANGE = "POST_REQUEST_SHIFT_CHANGE";
export const POST_REQUEST_SHIFT_CHANGE_SUCCESS = "POST_REQUEST_SHIFT_CHANGE_SUCCESS";
export const POST_REQUEST_SHIFT_CHANGE_FAILURE = "POST_REQUEST_SHIFT_CHANGE_FAILURE";


export const POST_CHANGE_SHIFT_CHANGE = "POST_CHANGE_SHIFT_CHANGE";
export const POST_CHANGE_SHIFT_CHANGE_SUCCESS = "POST_CHANGE_SHIFT_CHANGE_SUCCESS";
export const POST_CHANGE_SHIFT_CHANGE_FAILURE = "POST_CHANGE_SHIFT_CHANGE_FAILURE";


export const CURRENT_STATUS_TYPE = "CURRENT_STATUS_TYPE";

export const DESIGNATION_GROUP_DETAILS = "DESIGNATION_GROUP_DETAILS";


export const GET_HFWS_BRANCH_SHIFT = "GET_HFWS_BRANCH_SHIFT";
export const GET_HFWS_BRANCH_SHIFT_SUCCESS = "GET_HFWS_BRANCH_SHIFT_SUCCESS";
export const GET_HFWS_BRANCH_SHIFT_FAILURE = "GET_HFWS_BRANCH_SHIFT_FAILURE";