export const FETCH_ALL_BRANCHES_LIST = "FETCH_ALL_BRANCHES_LIST";
export const FETCH_ALL_BRANCHES_LIST_SUCCESS = "FETCH_ALL_BRANCHES_LIST_SUCCESS";
export const FETCH_ALL_BRANCHES_LIST_FAILURE = "FETCH_ALL_BRANCHES_LIST_FAILURE";



export const POST_BRANCH_ADDITION = "POST_BRANCH_ADDITION";
export const POST_BRANCH_ADDITION_SUCCESS = "POST_BRANCH_ADDITION_SUCCESS";
export const POST_BRANCH_ADDITION_FAILURE = "POST_BRANCH_ADDITION_FAILURE";

export const UPDATE_BRANCH_LOCATION_RADIUS = "UPDATE_BRANCH_LOCATION_RADIUS";
export const UPDATE_BRANCH_LOCATION_RADIUS_SUCCESS = "UPDATE_BRANCH_LOCATION_RADIUS_SUCCESS";
export const UPDATE_BRANCH_LOCATION_RADIUS_FAILURE = "UPDATE_BRANCH_LOCATION_RADIUS_FAILURE";

export const ENABLE_BRANCH_REFENCE = "ENABLE_BRANCH_REFENCE";
export const ENABLE_BRANCH_REFENCE_SUCCESS = "ENABLE_BRANCH_REFENCE_SUCCESS";
export const ENABLE_BRANCH_REFENCE_FAILURE = "ENABLE_BRANCH_REFENCE_FAILURE";

export const GET_EMPLOYEE_CHECKIN_ASSOCIATIONS = "GET_EMPLOYEE_CHECKIN_ASSOCIATIONS";
export const GET_EMPLOYEE_CHECKIN_ASSOCIATIONS_SUCCESS = "GET_EMPLOYEE_CHECKIN_ASSOCIATIONS_SUCCESS";
export const UPDATE_EMPLOYEE_CHECKIN_ASSOCIATIONS_REDUCER = "UPDATE_EMPLOYEE_CHECKIN_ASSOCIATIONS_REDUCER";

export const GET_EMPLOYEE_CHECKIN_ASSOCIATIONS_FAILURE = "GET_EMPLOYEE_CHECKIN_ASSOCIATIONS_FAILURE";

export const UPDATE_EMPLOYEE_CHECKIN_ASSOCIATIONS = "UPDATE_EMPLOYEE_CHECKIN_ASSOCIATIONS";
export const UPDATE_EMPLOYEE_CHECKIN_ASSOCIATIONS_SUCCESS = "UPDATE_EMPLOYEE_CHECKIN_ASSOCIATIONS_SUCCESS";
export const UPDATE_EMPLOYEE_CHECKIN_ASSOCIATIONS_FAILURE = "UPDATE_EMPLOYEE_CHECKIN_ASSOCIATIONS_FAILURE";

export const EDIT_BRANCH_NAME = "EDIT_BRANCH_NAME";
export const EDIT_BRANCH_NAME_SUCCESS = "EDIT_BRANCH_NAME_SUCCESS";
export const EDIT_BRANCH_NAME_FAILURE = "EDIT_BRANCH_NAME_FAILURE";

export const RESET_REDUCER = "RESET_REDUCER";

export const FETCH_LIST_ALL_BRANCHES_LIST = "FETCH_LIST_ALL_BRANCHES_LIST";
export const FETCH_LIST_ALL_BRANCHES_LIST_SUCCESS = "FETCH_LIST_ALL_BRANCHES_LIST_SUCCESS";
export const FETCH_LIST_ALL_BRANCHES_LIST_FAILURE = "FETCH_LIST_ALL_BRANCHES_LIST_FAILURE";


// delete Branch 

export const DELETE_BRANCH = "DELETE_BRANCH";
export const DELETE_BRANCH_SUCCESS = "DELETE_BRANCH_SUCCESS";
export const DELETE_BRANCH_FAILURE = "DELETE_BRANCH_FAILURE";