export const RESET_REDUCER = "RESET_REDUCER";

export const CREATE_GROUP = 'CREATE_GROUP';

/**
 * Add company Allowance
 */
export const ADD_COMPANY_ALLOWANCE = "ADD_COMPANY_ALLOWANCE";
export const ADD_COMPANY_ALLOWANCE_SUCCESS = "ADD_COMPANY_ALLOWANCE_SUCCESS";
export const ADD_COMPANY_ALLOWANCE_FAILURE = "ADD_COMPANY_ALLOWANCE_FAILURE";

/**
 * Add company deduction
 */
export const ADD_COMPANY_DEDUCTION = "ADD_COMPANY_DEDUCTION";
export const ADD_COMPANY_DEDUCTION_SUCCESS = "ADD_COMPANY_DEDUCTION_SUCCESS";
export const ADD_COMPANY_DEDUCTION_FAILURE = "ADD_COMPANY_DEDUCTION_FAILURE";

/**
 * get Tax Sections
 */
export const GET_TAX_SECTIONS = "GET_TAX_SECTIONS";
export const GET_TAX_SECTIONS_SUCCESS = "GET_TAX_SECTIONS_SUCCESS";
export const GET_TAX_SECTIONS_FAILURE = "GET_TAX_SECTIONS_FAILURE";

/**
 * add Allowance Group
 */
export const ADD_ALLOWANCE_GROUPS = "ADD_ALLOWANCE_GROUPS";
export const ADD_ALLOWANCE_GROUPS_SUCCESS = "ADD_ALLOWANCE_GROUPS_SUCCESS";
export const ADD_ALLOWANCE_GROUPS_FAILURE = "ADD_ALLOWANCE_GROUPS_FAILURE";


/**
 * get Allowance Groups
 */
export const GET_ALLOWANCE_GROUPS = "GET_ALLOWANCE_GROUPS";
export const GET_ALLOWANCE_GROUPS_SUCCESS = "GET_ALLOWANCE_GROUPS_SUCCESS";
export const GET_ALLOWANCE_GROUPS_FAILURE = "GET_ALLOWANCE_GROUPS_FAILURE";

/**
 * get Allowance Groups
 */
export const GET_ALLOWANCE_GROUPS_PAGINATED = "GET_ALLOWANCE_GROUPS_PAGINATED";
export const GET_ALLOWANCE_GROUPS_PAGINATED_SUCCESS = "GET_ALLOWANCE_GROUPS_PAGINATED_SUCCESS";
export const GET_ALLOWANCE_GROUPS_PAGINATED_FAILURE = "GET_ALLOWANCE_GROUPS_PAGINATED_FAILURE";

/**
 * get Allowance Group details
 */
export const GET_ALLOWANCE_GROUP_DETAILS = "GET_ALLOWANCE_GROUP_DETAILS";
export const GET_ALLOWANCE_GROUP_DETAILS_SUCCESS = "GET_ALLOWANCE_GROUP_DETAILS_SUCCESS";
export const GET_ALLOWANCE_GROUP_DETAILS_FAILURE = "GET_ALLOWANCE_GROUP_DETAILS_FAILURE";

/**
 * get salary Allowance
 */
export const GET_SALARY_ALLOWANCE = "GET_SALARY_ALLOWANCE";
export const GET_SALARY_ALLOWANCE_SUCCESS = "GET_SALARY_ALLOWANCE_SUCCESS";
export const GET_SALARY_ALLOWANCE_FAILURE = "GET_SALARY_ALLOWANCE_FAILURE";

/**
 * Get company allowance
 */
export const GET_COMPANY_ALLOWANCE = "GET_COMPANY_ALLOWANCE";
export const GET_COMPANY_ALLOWANCE_SUCCESS = "GET_COMPANY_ALLOWANCE_SUCCESS";
export const GET_COMPANY_ALLOWANCE_FAILURE = "GET_COMPANY_ALLOWANCE_FAILURE";

//setting selected allowance group item

export const SETTING_SELECTED_ALLOWANCE_GROUP_DETAILS = "SETTING_SELECTED_ALLOWANCE_GROUP_DETAILS"

//get company deductions

export const GET_COMPANY_DEDUCTIONS = "GET_COMPANY_DEDUCTIONS";
export const GET_COMPANY_DEDUCTIONS_SUCCESS = "GET_COMPANY_DEDUCTIONS_SUCCESS";
export const GET_COMPANY_DEDUCTIONS_FAILURE = "GET_COMPANY_DEDUCTIONS_FAILURE";

//get company deductions paginated

export const GET_COMPANY_DEDUCTIONS_PAGINATED = "GET_COMPANY_DEDUCTIONS_PAGINATED";
export const GET_COMPANY_DEDUCTIONS_PAGINATED_SUCCESS = "GET_COMPANY_DEDUCTIONS_PAGINATED_SUCCESS";
export const GET_COMPANY_DEDUCTIONS_PAGINATED_FAILURE = "GET_COMPANY_DEDUCTIONS_PAGINATED_FAILURE";

//setting selected deduction details

export const SETTING_SELECTED_DEDUCTION_DETAILS = "SETTING_SELECTED_DEDUCTION_DETAILS"


/**
 * add Employee Salary
 */
export const ADD_EMPLOYEE_SALARY_DEFINITION = "ADD_EMPLOYEE_SALARY_DEFINITION";
export const ADD_EMPLOYEE_SALARY_DEFINITION_SUCCESS = "ADD_EMPLOYEE_SALARY_DEFINITION_SUCCESS";
export const ADD_EMPLOYEE_SALARY_DEFINITION_FAILURE = "ADD_EMPLOYEE_SALARY_DEFINITION_FAILURE";

/**
 * setting selected employee details
 */

export const SETTING_SELECTED_EMPLOYEE_DETAILS = "SETTING_SELECTED_EMPLOYEE_DETAILS"


/**
 * get Employee Salary
 */

export const GET_EMPLOYEE_SALARY_DEFINITION = "GET_EMPLOYEE_SALARY_DEFINITION";
export const GET_EMPLOYEE_SALARY_DEFINITION_SUCCESS = "GET_EMPLOYEE_SALARY_DEFINITION_SUCCESS";
export const GET_EMPLOYEE_SALARY_DEFINITION_FAILURE = "GET_EMPLOYEE_SALARY_DEFINITION_FAILURE";

/**
 * is edit salary definition
 */

export const IS_EDIT_SALARY_DEFINITION = "IS_EDIT_SALARY_DEFINITION"


// get Earnings

export const GET_EARNINGS = 'GET_EARNINGS'
export const GET_EARNINGS_SUCCESS = "GET_EARNINGS_SUCCESS";
export const GET_EARNINGS_FAILURE = "GET_EARNINGS_FAILURE";


// ADD_COMPANY_INCENTIVE

export const SET_COMPANY_INCENTIVE = 'SET_COMPANY_INCENTIVE'
export const SET_COMPANY_INCENTIVE_SUCCESS = "SET_COMPANY_INCENTIVE_SUCCESS";
export const SET_COMPANY_INCENTIVE_FAILURE = "SET_COMPANY_INCENTIVE_FAILURE";


// getCompanyIncentives


export const GET_COMPANY_INCENTIVE = 'GET_COMPANY_INCENTIVE'
export const GET_COMPANY_INCENTIVE_SUCCESS = "GET_COMPANY_INCENTIVE_SUCCESS";
export const GET_COMPANY_INCENTIVE_FAILURE = "GET_COMPANY_INCENTIVE_FAILURE";

// set Incentive details 

export const SETTING_SELECTED_INCENTIVE_DETAILS = "SETTING_SELECTED_INCENTIVE_DETAILS"
