export const RESET_GUEST = 'RESET_GUEST'

export const POST_TASK_BY_GUEST = 'POST_TASK_BY_GUEST'
export const POST_TASK_BY_GUEST_SUCCESS = 'POST_TASK_BY_GUEST_SUCCESS'
export const POST_TASK_BY_GUEST_FAILURE = 'POST_TASK_BY_GUEST_FAILURE'

export const FETCH_GUEST_TASKS = 'FETCH_GUEST_TASKS'
export const FETCH_GUEST_TASKS_SUCCESS = 'FETCH_GUEST_TASKS_SUCCESS'
export const FETCH_GUEST_TASKS_FAILURE = 'FETCH_GUEST_TASKS_FAILURE'

export const FETCH_GUEST_TASK_DETAILS = 'FETCH_GUEST_TASK_DETAILS'
export const FETCH_GUEST_TASK_DETAILS_SUCCESS = 'FETCH_GUEST_TASK_DETAILS_SUCCESS'
export const FETCH_GUEST_TASK_DETAILS_FAILURE = 'FETCH_GUEST_TASK_DETAILS_FAILURE'

export const SELECTED_GUEST_TASK_ITEM = 'SELECTED_GUEST_TASK_ITEM'

export const CODE_OUTPUT_DATA = "CODE_OUTPUT_DATA"
export const GUEST_TASK_CODE = "GUEST_TASK_CODE"

export const FETCH_GUEST_TASK_DETAILS_OPEN = "FETCH_GUEST_TASK_DETAILS_OPEN"
export const FETCH_GUEST_TASK_DETAILS_OPEN_SUCCESS = "FETCH_GUEST_TASK_DETAILS_OPEN_SUCCESS"
export const FETCH_GUEST_TASK_DETAILS_OPEN_FAILURE = "FETCH_GUEST_TASK_DETAILS_OPEN_FAILURE"

export const DOWNLOAD_TASK_TYPE = "DOWNLOAD_TASK_TYPE"
export const FETCH_TASK_OBJECT = "FETCH_TASK_OBJECT"






