///////////////////////  Version 2 ///////////////////////////////

export const RESET_STUDENT = 'RESET_STUDENT'

export const YOUTUBE_VIDEO_TITLE = "YOUTUBE_VIDEO_TITLE"

//get user digital profile

export const FETCH_USER_DIGITAL_PROFILE = "FETCH_USER_DIGITAL_PROFILE";
export const FETCH_USER_DIGITAL_PROFILE_SUCCESS = "FETCH_USER_DIGITAL_PROFILE_SUCCESS";
export const FETCH_USER_DIGITAL_PROFILE_FAILURE = "FETCH_USER_DIGITAL_PROFILE_FAILURE";

//add user digital profile

export const POST_USER_DIGITAL_PROFILE = "POST_USER_DIGITAL_PROFILE";
export const POST_USER_DIGITAL_PROFILE_SUCCESS = "POST_USER_DIGITAL_PROFILE_SUCCESS";
export const POST_USER_DIGITAL_PROFILE_FAILURE = "POST_USER_DIGITAL_PROFILE_FAILURE";


//get user details

export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
export const FETCH_USER_DETAILS_FAILURE = "FETCH_USER_DETAILS_FAILURE";

// setting flowdiagram image

export const SETTING_FLOW_DIAGRAM_IMAGE = 'SETTING_FLOW_DIAGRAM_IMAGE' 