export const FETCH_DASHBOARD = "FETCH_DASHBOARD";
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS";
export const FETCH_DASHBOARD_FAIL = "FETCH_DASHBOARD_FAIL";

export const GET_CHECK_IN_DETAILED_LOG = "GET_CHECK_IN_DETAILED_LOG";
export const GET_CHECK_IN_DETAILED_LOG_SUCCESS = "GET_CHECK_IN_DETAILED_LOG_SUCCESS";
export const GET_CHECK_IN_DETAILED_LOG_FAIL = "GET_CHECK_IN_DETAILED_LOG_FAIL";

export const URL_CHECK_IN = "URL_CHECK_IN";
export const URL_CHECK_IN_SUCCESS = "URL_CHECK_IN_SUCCESS";
export const URL_CHECK_IN_FAIL = "URL_CHECK_IN_FAIL";

export const POST_DAILY_LOG = "POST_DAILY_LOG";
export const POST_DAILY_LOG_SUCCESS = "POST_DAILY_LOG_SUCCESS";
export const POST_DAILY_LOG_FAIL = "POST_DAILY_LOG_FAIL";

export const URL_DELETE_USER = "URL_DELETE_USER";
export const URL_DELETE_USER_SUCCESS = "URL_DELETE_USER_SUCCESS";
export const URL_DELETE_USER_FAIL = "URL_DELETE_USER_FAIL";

export const EDIT_PROFILE_PICTURE = "EDIT_PROFILE_PICTURE";
export const EDIT_PROFILE_PICTURE_SUCCESS = "EDIT_PROFILE_PICTURE_USER_SUCCESS";
export const EDIT_PROFILE_PICTURE_FAIL = "EDIT_PROFILE_PICTURE_FAIL";


export const SET_HIERARCHICAL_BRANCH_IDS = "SET_HIERARCHICAL_BRANCH_IDS";
export const SET_HIERARCHICAL_BRANCH_INCLUDE_CHILD = "SET_HIERARCHICAL_BRANCH_INCLUDE_CHILD";

export const SET_HIERARCHICAL_ALL_BRANCH_IDS = "SET_HIERARCHICAL_ALL_BRANCH_IDS";

export const SET_MULTISELECT_ALL_BRANCH_IDS = "SET_MULTISELECT_ALL_BRANCH_IDS";





export const RESET_REDUCER = "RESET_REDUCER";
export const MATCH_ROUTE_NAME = "MATCH_ROUTE_NAME";


/**
 * face Validation
 */

export const EMPLOYEE_FACE_FAILURE_LIST = "EMPLOYEE_FACE_FAILURE_LIST";
export const EMPLOYEE_FACE_FAILURE_LIST_SUCCESS = "EMPLOYEE_FACE_FAILURE_LIST_SUCCESS";
export const EMPLOYEE_FACE_FAILURE_LIST_FAIL = "EMPLOYEE_FACE_FAILURE_LIST_FAIL";

/**
 * changeEmployeeFaceValidationRequest
 */

export const CHANGE_EMPLOYEE_FACE_VALIDATION_REQUEST = "CHANGE_EMPLOYEE_FACE_VALIDATION_REQUEST";
export const CHANGE_EMPLOYEE_FACE_VALIDATION_REQUEST_SUCCESS = "CHANGE_EMPLOYEE_FACE_VALIDATION_REQUEST_SUCCESS";
export const CHANGE_EMPLOYEE_FACE_VALIDATION_REQUEST_FAIL = "CHANGE_EMPLOYEE_FACE_VALIDATION_REQUEST_FAIL";



export const CURRENT_FACE_STATUS_TYPE = "CURRENT_FACE_STATUS_TYPE";


//Face Re-Register Request

export const FACE_RE_REGISTER_REQUEST = "FACE_RE_REGISTER_REQUEST"
export const FACE_RE_REGISTER_REQUEST_SUCCESS = "FACE_RE_REGISTER_REQUEST_SUCCESS";
export const FACE_RE_REGISTER_REQUEST_FAIL = "FACE_RE_REGISTER_REQUEST_FAIL";


// Face Re-Register Change Status

export const FACE_RE_REGISTER_CHANGE_STATUS = "FACE_RE_REGISTER_CHANGE_STATUS"
export const FACE_RE_REGISTER_CHANGE_STATUS_SUCCESS = "FACE_RE_REGISTER_CHANGE_STATUS_SUCCESS";
export const FACE_RE_REGISTER_CHANGE_STATUS_FAIL = "FACE_RE_REGISTER_CHANGE_STATUS_FAIL";


//face Re-register Employee Request 

export const EMPLOYEE_FACE_RE_REGISTER_REQUEST = "EMPLOYEE_FACE_RE_REGISTER_REQUEST"
export const EMPLOYEE_FACE_RE_REGISTER_REQUEST_SUCCESS = "EMPLOYEE_FACE_RE_REGISTER_REQUEST_SUCCESS";
export const EMPLOYEE_FACE_RE_REGISTER_REQUEST_FAIL = "EMPLOYEE_FACE_RE_REGISTER_REQUEST_FAIL";

//employee enable Face ReRegister

export const EMPLOYEE_ENABLE_FACE_RE_REGISTER_ACTION = "EMPLOYEE_ENABLE_FACE_RE_REGISTER_ACTION"
export const EMPLOYEE_ENABLE_FACE_RE_REGISTER_ACTION_SUCCESS = "EMPLOYEE_ENABLE_FACE_RE_REGISTER_ACTION_SUCCESS";
export const EMPLOYEE_ENABLE_FACE_RE_REGISTER_ACTION_FAIL = "EMPLOYEE_ENABLE_FACE_RE_REGISTER_ACTION_FAIL";


//

export const TRIGGER_HIERARCHICAL = 'TRIGGER_HIERARCHICAL'