export const RESET_DASHBOARD = 'RESET_DASHBOARD'


export const IS_SUPER_ADMIN = "IS_SUPER_ADMIN"

export const FETCH_TASK_DETAILS = 'FETCH_TASK_DETAILS';
export const FETCH_TASK_DETAILS_SUCCESS = 'FETCH_TASK_DETAILS_SUCCESS';
export const FETCH_TASK_DETAILS_FAILURE = 'FETCH_TASK_DETAILS_FAILURE'

export const FETCH_COURSES = 'FETCH_COURSES';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE'

export const FETCH_COURSE_SECTIONS = 'FETCH_COURSE_SECTIONS';
export const FETCH_COURSE_SECTIONS_SUCCESS = 'FETCH_COURSE_SECTIONS_SUCCESS';
export const FETCH_COURSE_SECTIONS_FAILURE = 'FETCH_COURSE_SECTIONS_FAILURE'

export const FETCH_COURSE_TOPICS = 'FETCH_COURSES_TOPICS';
export const FETCH_COURSE_TOPICS_SUCCESS = 'FETCH_COURSES_TOPICS_SUCCESS';
export const FETCH_COURSE_TOPICS_FAILURE = 'FETCH_COURSES_TOPICS_FAILURE'

export const FETCH_COURSE_TOPIC_TASKS = 'FETCH_COURSE_TOPIC_TASKS';
export const FETCH_COURSE_TOPIC_TASKS_SUCCESS = 'FETCH_COURSE_TOPIC_TASKS_SUCCESS';
export const FETCH_COURSE_TOPIC_TASKS_FAILURE = 'FETCH_COURSE_TOPIC_TASKS_FAILURE'

export const SET_COURSE_TOPIC_NAME = 'SET_COURSE_TOPIC_NAME'

export const TOGGLE_SIDE_NAV_OPEN = 'TOGGLE_SIDE_NAV_OPEN'


export const POST_GENERIC_CRUD_DETAILS = 'POST_GENERIC_CRUD_DETAILS';
export const POST_GENERIC_CRUD_DETAILS_SUCCESS = 'POST_GENERIC_CRUD_DETAILS_SUCCESS';
export const POST_GENERIC_CRUD_DETAILS_FAILURE = 'POST_GENERIC_CRUD_DETAILS_FAILURE'

export const POST_GENERIC_BATCH_CRUD_DETAILS = 'POST_GENERIC_BATCH_CRUD_DETAILS';
export const POST_GENERIC_BATCH_CRUD_DETAILS_SUCCESS = 'POST_GENERIC_BATCH_CRUD_DETAILS_SUCCESS';
export const POST_GENERIC_BATCH_CRUD_DETAILS_FAILURE = 'POST_GENERIC_BATCH_CRUD_DETAILS_FAILURE';

export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";

export const ADD_DESIGNATION = "ADD_DESIGNATION";
export const ADD_DESIGNATION_SUCCESS = "ADD_DESIGNATION_SUCCESS";
export const ADD_DESIGNATION_FAILURE = "ADD_DESIGNATION_FAILURE";

export const FETCH_DESIGNATION = "FETCH_DESIGNATION";
export const FETCH_DESIGNATION_SUCCESS = "FETCH_DESIGNATION_SUCCESS";
export const FETCH_DESIGNATION_FAILURE = "FETCH_DESIGNATION_FAILURE";

export const FETCH_DEPARTMENT = "FETCH_DEPARTMENT";
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_FAILURE = "FETCH_DEPARTMENT_FAILURE";

export const SET_CURRENT_COURSE_SECTION = "SET_CURRENT_COURSE_SECTION";
export const IS_DND_MODAL_OPEN = 'IS_DND_MODAL_OPEN';

export const ADD_STUDENT = "ADD_STUDENT";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_FAILURE = "ADD_STUDENT_FAILURE";

export const FETCH_STUDENTS_LIST = "FETCH_STUDENTS_LIST";
export const FETCH_STUDENTS_LIST_SUCCESS = "FETCH_STUDENTS_LIST_SUCCESS";
export const FETCH_STUDENTS_LIST_FAILURE = "FETCH_STUDENTS_LIST_FAILURE";

export const ADD_FACULTY = "ADD_FACULTY";
export const ADD_FACULTY_SUCCESS = "ADD_FACULTY_SUCCESS";
export const ADD_FACULTY_FAILURE = "ADD_FACULTY_FAILURE";

export const FETCH_FACULTIES_LIST = "FETCH_FACULTIES_LIST";
export const FETCH_FACULTIES_LIST_SUCCESS = "FETCH_FACULTIES_LIST_SUCCESS";
export const FETCH_FACULTIES_LIST_FAILURE = "FETCH_FACULTIES_LIST_FAILURE";

export const FETCH_APPROVER_LIST = "FETCH_APPROVER_LIST";
export const FETCH_APPROVER_LIST_SUCCESS = "FETCH_APPROVER_LIST_SUCCESS";
export const FETCH_APPROVER_LIST_FAILURE = "FETCH_APPROVER_LIST_FAILURE";

export const FETCH_REFERER_LIST = "FETCH_REFERER_LIST";
export const FETCH_REFERER_LIST_SUCCESS = "FETCH_REFERER_LIST_SUCCESS";
export const FETCH_REFERER_LIST_FAILURE = "FETCH_REFERER_LIST_FAILURE";

export const SETTING_CURRENT_COURSE = "SETTING_CURRENT_COURSE"

export const FETCH_STUDENTS_DETAILS = "FETCH_STUDENTS_DETAILS";
export const FETCH_STUDENTS_DETAILS_SUCCESS = "FETCH_STUDENTS_DETAILS_SUCCESS";
export const FETCH_STUDENTS_DETAILS_FAILURE = "FETCH_STUDENTS_DETAILS_FAILURE";

export const SETTING_CURRENT_TASK_ITEM = "SETTING_CURRENT_TASK_ITEM";

export const FETCH_DASHBOARD_DETAILS = "FETCH_DASHBOARD_DETAILS";
export const FETCH_DASHBOARD_DETAILS_SUCCESS = "FETCH_DASHBOARD_DETAILS_SUCCESS";
export const FETCH_DASHBOARD_DETAILS_FAILURE = "FETCH_DASHBOARD_DETAILS_FAILURE";

export const SETTING_SELECTED_FACULTY_ID = "SETTING_SELECTED_FACULTY_ID";

export const EDIT_USER_REGISTRATION = 'EDIT_USER_REGISTRATION'

export const POST_RAISE_ANONYMOUS_COMPLAINT = "POST_RAISE_ANONYMOUS_COMPLAINT";
export const POST_RAISE_ANONYMOUS_COMPLAINT_SUCCESS = "POST_RAISE_ANONYMOUS_COMPLAINT_SUCCESS";
export const POST_RAISE_ANONYMOUS_COMPLAINT_FAILURE = "POST_RAISE_ANONYMOUS_COMPLAINT_FAILURE";

export const FETCH_COURSE_IDE = "FETCH_COURSE_IDE";
export const FETCH_COURSE_IDE_SUCCESS = "FETCH_COURSE_IDE_SUCCESS";
export const FETCH_COURSE_IDE_FAILURE = "FETCH_COURSE_IDE_FAILURE";

export const COURSE_RENDERER = "COURSE_RENDERER"

export const FETCH_STUDENT_COURSE_TASKS_FACULTY = "FETCH_STUDENT_COURSE_TASKS_FACULTY";
export const FETCH_STUDENT_COURSE_TASKS_FACULTY_SUCCESS = "FETCH_STUDENT_COURSE_TASKS_FACULTY_SUCCESS";
export const FETCH_STUDENT_COURSE_TASKS_FACULTY_FAILURE = "FETCH_STUDENT_COURSE_TASKS_FACULTY_FAILURE";

export const FETCH_STUDENT_COURSE_TASK_DETAILS_FACULTY = "FETCH_STUDENT_COURSE_TASK_DETAILS_FACULTY";
export const FETCH_STUDENT_COURSE_TASK_DETAILS_FACULTY_SUCCESS = "FETCH_STUDENT_COURSE_TASK_DETAILS_FACULTY_SUCCESS";
export const FETCH_STUDENT_COURSE_TASK_DETAILS_FACULTY_FAILURE = "FETCH_STUDENT_COURSE_TASK_DETAILS_FACULTY_FAILURE";

export const VIEW_STUDENT_TASK_DETAILS_ID = "VIEW_STUDENT_TASK_DETAILS_ID";

export const POST_SUBMIT_STUDENT_COURSE_PENDING_APPROVAL_TASK = 'POST_SUBMIT_STUDENT_COURSE_PENDING_APPROVAL_TASK'
export const POST_SUBMIT_STUDENT_COURSE_PENDING_APPROVAL_TASK_SUCCESS = 'POST_SUBMIT_STUDENT_COURSE_PENDING_APPROVAL_TASK_SUCCESS'
export const POST_SUBMIT_STUDENT_COURSE_PENDING_APPROVAL_TASK_FAILURE = 'POST_SUBMIT_STUDENT_COURSE_PENDING_APPROVAL_TASK_FAILURE'

export const POST_TASK_EVENT = 'POST_TASK_EVENT'
export const POST_TASK_EVENT_SUCCESS = 'POST_TASK_EVENT_SUCCESS'
export const POST_TASK_EVENT_FAILURE = 'POST_TASK_EVENT_FAILURE'

export const FETCH_TASK_EVENTS = 'FETCH_TASK_EVENTS'
export const FETCH_TASK_EVENTS_SUCCESS = 'FETCH_TASK_EVENTS_SUCCESS'
export const FETCH_TASK_EVENTS_FAILURE = 'FETCH_TASK_EVENTS_FAILURE'

export const FETCH_USER_ONLINE_ACTIVE_LOG = 'FETCH_USER_ONLINE_ACTIVE_LOG'
export const FETCH_USER_ONLINE_ACTIVE_LOG_SUCCESS = 'FETCH_USER_ONLINE_ACTIVE_LOG_SUCCESS'
export const FETCH_USER_ONLINE_ACTIVE_LOG_FAILURE = 'FETCH_USER_ONLINE_ACTIVE_LOG_FAILURE'

export const FETCH_TOPIC_TASK_TYPES = 'FETCH_TOPIC_TASK_TYPES'
export const FETCH_TOPIC_TASK_TYPES_SUCCESS = 'FETCH_TOPIC_TASK_TYPES_SUCCESS'
export const FETCH_TOPIC_TASK_TYPES_FAILURE = 'FETCH_TOPIC_TASK_TYPES_FAILURE'


export const FETCH_PAGE_SECTIONS = 'FETCH_PAGE_SECTIONS'
export const FETCH_PAGE_SECTIONS_SUCCESS = 'FETCH_PAGE_SECTIONS_SUCCESS'
export const FETCH_PAGE_SECTIONS_FAILURE = 'FETCH_PAGE_SECTIONS_FAILURE'

export const FETCH_SECTION_TYPE_TITLE = 'FETCH_SECTION_TYPE_TITLE'
export const FETCH_SECTION_TYPE_TITLE_SUCCESS = 'FETCH_SECTION_TYPE_TITLE_SUCCESS'
export const FETCH_SECTION_TYPE_TITLE_FAILURE = 'FETCH_SECTION_TYPE_TITLE_FAILURE'

export const FETCH_SECTION_TYPE_IMAGE = 'FETCH_SECTION_TYPE_IMAGE'
export const FETCH_SECTION_TYPE_IMAGE_SUCCESS = 'FETCH_SECTION_TYPE_IMAGE_SUCCESS'
export const FETCH_SECTION_TYPE_IMAGE_FAILURE = 'FETCH_SECTION_TYPE_IMAGE_FAILURE'

export const FETCH_SECTION_TYPE_VIDEO = 'FETCH_SECTION_TYPE_VIDEO'
export const FETCH_SECTION_TYPE_VIDEO_SUCCESS = 'FETCH_SECTION_TYPE_VIDEO_SUCCESS'
export const FETCH_SECTION_TYPE_VIDEO_FAILURE = 'FETCH_SECTION_TYPE_VIDEO_FAILURE'

export const FETCH_SECTION_TYPE_PARAGRAPH = 'FETCH_SECTION_TYPE_PARAGRAPH'
export const FETCH_SECTION_TYPE_PARAGRAPH_SUCCESS = 'FETCH_SECTION_TYPE_PARAGRAPH_SUCCESS'
export const FETCH_SECTION_TYPE_PARAGRAPH_FAILURE = 'FETCH_SECTION_TYPE_PARAGRAPH_FAILURE'

export const FETCH_SECTION_TYPE_LIST = 'FETCH_SECTION_TYPE_LIST'
export const FETCH_SECTION_TYPE_LIST_SUCCESS = 'FETCH_SECTION_TYPE_LIST_SUCCESS'
export const FETCH_SECTION_TYPE_LIST_FAILURE = 'FETCH_SECTION_TYPE_LIST_FAILURE'

export const FETCH_SECTION_TYPE_MD = 'FETCH_SECTION_TYPE_MD'
export const FETCH_SECTION_TYPE_MD_SUCCESS = 'FETCH_SECTION_TYPE_MD_SUCCESS'
export const FETCH_SECTION_TYPE_MD_FAILURE = 'FETCH_SECTION_TYPE_MD_FAILURE'


export const EDIT_PAGE_SECTION_TYPE = "EDIT_PAGE_SECTION_TYPE";

export const FETCH_USER_REMARK = 'FETCH_USER_REMARK'
export const FETCH_USER_REMARK_SUCCESS = 'FETCH_USER_REMARK_SUCCESS'
export const FETCH_USER_REMARK_FAILURE = 'FETCH_USER_REMARK_FAILURE'

export const FETCH_USERS_REMARK = 'FETCH_USERS_REMARK'
export const FETCH_USERS_REMARK_SUCCESS = 'FETCH_USERS_REMARK_SUCCESS'
export const FETCH_USERS_REMARK_FAILURE = 'FETCH_USERS_REMARK_FAILURE'

export const REMARK_USERID = 'REMARK_USERID'
export const IS_SHOW_STUDENTS_LIST = "IS_SHOW_STUDENT_LIST"

export const IS_SHOW_FACULTIES_LIST = "IS_SHOW_FACULTIES_LIST"

export const IS_BACK = "IS_BACK"

export const CURRENT_NAV = "CURRENT_NAV"

export const POST_BRANCH = 'POST_BRANCH'
export const POST_BRANCH_SUCCESS = 'POST_BRANCH_SUCCESS'
export const POST_BRANCH_FAILURE = 'POST_BRANCH_FAILURE'

export const POST_BULK_UPLOAD_COURSE_SECTIONS = "POST_BULK_UPLOAD_COURSE_SECTIONS"
export const POST_BULK_UPLOAD_COURSE_SECTIONS_SUCCESS = "POST_BULK_UPLOAD_COURSE_SECTIONS_SUCCESS"
export const POST_BULK_UPLOAD_COURSE_SECTIONS_FAILURE = "POST_BULK_UPLOAD_COURSE_SECTIONS_FAILURE"

export const POST_BULK_UPLOAD_COURSE_TOPICS = "POST_BULK_UPLOAD_COURSE_TOPICS"
export const POST_BULK_UPLOAD_COURSE_TOPICS_SUCCESS = "POST_BULK_UPLOAD_COURSE_TOPICS_SUCCESS"
export const POST_BULK_UPLOAD_COURSE_TOPICS_FAILURE = "POST_BULK_UPLOAD_COURSE_TOPICS_FAILURE"

export const POST_BULK_UPLOAD_COURSE_TASKS = "POST_BULK_UPLOAD_COURSE_TASKS"
export const POST_BULK_UPLOAD_COURSE_TASKS_SUCCESS = "POST_BULK_UPLOAD_COURSE_TASKS_SUCCESS"
export const POST_BULK_UPLOAD_COURSE_TASKS_FAILURE = "POST_BULK_UPLOAD_COURSE_TASKS_FAILURE"

export const FETCH_COURSE_TEMPLATES = "FETCH_COURSE_TEMPLATES"
export const FETCH_COURSE_TEMPLATES_SUCCESS = "FETCH_COURSE_TEMPLATES_SUCCESS"
export const FETCH_COURSE_TEMPLATES_FAILURE = "FETCH_COURSE_TEMPLATES_FAILURE"

export const SELECTED_FACULTY_DETAILS = 'SELECTED_FACULTY_DETAILS'




/**
 * bulk upload
 */
export const POST_BULK_UPLOAD_COURSES = "POST_BULK_UPLOAD_COURSES";
export const POST_BULK_UPLOAD_COURSES_SUCCESS = "POST_BULK_UPLOAD_COURSES_SUCCESS";
export const POST_BULK_UPLOAD_COURSES_FAILURE = "POST_BULK_UPLOAD_COURSES_FAILURE";

export const POST_BULK_UPLOAD_SECTION = "POST_BULK_UPLOAD_SECTION";
export const POST_BULK_UPLOAD_SECTION_SUCCESS = "POST_BULK_UPLOAD_SECTION_SUCCESS";
export const POST_BULK_UPLOAD_SECTION_FAILURE = "POST_BULK_UPLOAD_SECTION_FAILURE";

export const POST_BULK_UPLOAD_TOPICS = "POST_BULK_UPLOAD_TOPICS";
export const POST_BULK_UPLOAD_TOPICS_SUCCESS = "POST_BULK_UPLOAD_TOPICS_SUCCESS";
export const POST_BULK_UPLOAD_TOPICS_FAILURE = "POST_BULK_UPLOAD_TOPICS_FAILURE";

export const POST_BULK_UPLOAD_TASKS = "POST_BULK_UPLOAD_TASKS";
export const POST_BULK_UPLOAD_TASKS_SUCCESS = "POST_BULK_UPLOAD_TASKS_SUCCESS";
export const POST_BULK_UPLOAD_TASKS_FAILURE = "POST_BULK_UPLOAD_TASKS_FAILURE";

export const GET_BULK_UPLOAD_TEMPLATES = "GET_BULK_UPLOAD_TEMPLATES";
export const GET_BULK_UPLOAD_TEMPLATES_SUCCESS = "GET_BULK_UPLOAD_TEMPLATES_SUCCESS";
export const GET_BULK_UPLOAD_TEMPLATES_FAILURE = "GET_BULK_UPLOAD_TEMPLATES_FAILURE";

export const POST_BULK_UPLOAD_STUDENTS = "POST_BULK_UPLOAD_STUDENTS";
export const POST_BULK_UPLOAD_STUDENTS_SUCCESS = "POST_BULK_UPLOAD_STUDENTS_SUCCESS";
export const POST_BULK_UPLOAD_STUDENTS_FAILURE = "POST_BULK_UPLOAD_STUDENTS_FAILURE";

export const POST_BULK_UPLOAD_FACULTIES = "POST_BULK_UPLOAD_FACULTIES";
export const POST_BULK_UPLOAD_FACULTIES_SUCCESS = "POST_BULK_UPLOAD_FACULTIES_SUCCESS";
export const POST_BULK_UPLOAD_FACULTIES_FAILURE = "POST_BULK_UPLOAD_FACULTIES_FAILURE";

export const FETCH_EMPLOYEES_TEMPLATES = "FETCH_EMPLOYEES_TEMPLATES";
export const FETCH_EMPLOYEES_TEMPLATES_SUCCESS = "FETCH_EMPLOYEES_TEMPLATES_SUCCESS";
export const FETCH_EMPLOYEES_TEMPLATES_FAILURE = "FETCH_EMPLOYEES_TEMPLATES_FAILURE";

export const POST_USER_REMARKS = "POST_USER_REMARKS";
export const POST_USER_REMARKS_SUCCESS = "POST_USER_REMARKS_SUCCESS";
export const POST_USER_REMARKS_FAILURE = "POST_USER_REMARKS_FAILURE";

export const POST_SUBMIT_USER_REMARKS_APPROVAL = "POST_SUBMIT_USER_REMARKS_APPROVAL";
export const POST_SUBMIT_USER_REMARKS_APPROVAL_SUCCESS = "POST_SUBMIT_USER_REMARKS_APPROVAL_SUCCESS";
export const POST_SUBMIT_USER_REMARKS_APPROVAL_FAILURE = "POST_SUBMIT_USER_REMARKS_APPROVAL_FAILURE";

export const POST_SUBMIT_TASK_APPROVAL_BY_FACULTY = "POST_SUBMIT_TASK_APPROVAL_BY_FACULTY";
export const POST_SUBMIT_TASK_APPROVAL_BY_FACULTY_SUCCESS = "POST_SUBMIT_TASK_APPROVAL_BY_FACULTY_SUCCESS";
export const POST_SUBMIT_TASK_APPROVAL_BY_FACULTY_FAILURE = "POST_SUBMIT_TASK_APPROVAL_BY_FACULTY_FAILURE";

export const POST_ADD_COURSE = "POST_ADD_COURSE";
export const POST_ADD_COURSE_SUCCESS = "POST_ADD_COURSE_SUCCESS";
export const POST_ADD_COURSE_FAILURE = "POST_ADD_COURSE_FAILURE";

export const POST_ADD_COURSE_SECTION = "POST_ADD_COURSE_SECTION";
export const POST_ADD_COURSE_SECTION_SUCCESS = "POST_ADD_COURSE_SECTION_SUCCESS";
export const POST_ADD_COURSE_SECTION_FAILURE = "POST_ADD_COURSE_SECTION_FAILURE";

export const POST_ADD_COURSE_TOPIC = "POST_ADD_COURSE_TOPIC";
export const POST_ADD_COURSE_TOPIC_SUCCESS = "POST_ADD_COURSE_TOPIC_SUCCESS";
export const POST_ADD_COURSE_TOPIC_FAILURE = "POST_ADD_COURSE_TOPIC_FAILURE";

export const POST_ADD_COURSE_TASK = "POST_ADD_COURSE_TASK";
export const POST_ADD_COURSE_TASK_SUCCESS = "POST_ADD_COURSE_TASK_SUCCESS";
export const POST_ADD_COURSE_TASK_FAILURE = "POST_ADD_COURSE_TASK_FAILURE";

export const DO_EDIT_QUESTION = 'DO_EDIT_QUESTION';

export const POST_ADD_BATCH = "POST_ADD_BATCH";
export const POST_ADD_BATCH_SUCCESS = "POST_ADD_BATCH_SUCCESS";
export const POST_ADD_BATCH_FAILURE = "POST_ADD_BATCH_FAILURE";

export const POST_ADD_WEEKLY_CALENDAR = "POST_ADD_WEEKLY_CALENDAR";
export const POST_ADD_WEEKLY_CALENDAR_SUCCESS = "POST_ADD_WEEKLY_CALENDAR_SUCCESS";
export const POST_ADD_WEEKLY_CALENDAR_FAILURE = "POST_ADD_WEEKLY_CALENDAR_FAILURE";

export const FETCH_COURSE_BATCHES = "FETCH_COURSE_BATCHES";
export const FETCH_COURSE_BATCHES_SUCCESS = "FETCH_COURSE_BATCHES_SUCCESS";
export const FETCH_COURSE_BATCHES_FAILURE = "FETCH_COURSE_BATCHES_FAILURE";

export const SETTING_SELECTED_BATCH_DETAILS = "SETTING_SELECTED_BATCH_DETAILS"

export const FETCH_COURSE_BATCH_DETAILS = "FETCH_COURSE_BATCH_DETAILS";
export const FETCH_COURSE_BATCH_DETAILS_SUCCESS = "FETCH_COURSE_BATCH_DETAILS_SUCCESS";
export const FETCH_COURSE_BATCH_DETAILS_FAILURE = "FETCH_COURSE_BATCH_DETAILS_FAILURE";

export const ASSIGN_COURSE_BATCH_TO_STUDENT = "ASSIGN_COURSE_BATCH_TO_STUDENT";
export const ASSIGN_COURSE_BATCH_TO_STUDENT_SUCCESS = "ASSIGN_COURSE_BATCH_TO_STUDENT_SUCCESS";
export const ASSIGN_COURSE_BATCH_TO_STUDENT_FAILURE = "ASSIGN_COURSE_BATCH_TO_STUDENT_FAILURE";

export const FETCH_BATCH_STUDENT = "FETCH_BATCH_STUDENT";
export const FETCH_BATCH_STUDENT_SUCCESS = "FETCH_BATCH_STUDENT_SUCCESS";
export const FETCH_BATCH_STUDENT_FAILURE = "FETCH_BATCH_STUDENT_FAILURE";

export const FETCH_COURSE_BATCH_ADDED_STUDENTS = "FETCH_COURSE_BATCH_ADDED_STUDENTS";
export const FETCH_COURSE_BATCH_ADDED_STUDENTS_SUCCESS = "FETCH_COURSE_BATCH_ADDED_STUDENTS_SUCCESS";
export const FETCH_COURSE_BATCH_ADDED_STUDENTS_FAILURE = "FETCH_COURSE_BATCH_ADDED_STUDENTS_FAILURE";

export const POST_BATCH_VIDEO_CALL_USERS = 'POST_BATCH_VIDEO_CALL_USERS'
export const POST_BATCH_VIDEO_CALL_USERS_SUCCESS = 'POST_BATCH_VIDEO_CALL_USERS_SUCCESS'
export const POST_BATCH_VIDEO_CALL_USERS_FAILURE = 'POST_BATCH_VIDEO_CALL_USERS_FAILURE'


export const FETCH_BATCH_VIDEO_CALL_USERS = 'FETCH_BATCH_VIDEO_CALL_USERS'
export const FETCH_BATCH_VIDEO_CALL_USERS_SUCCESS = 'FETCH_BATCH_VIDEO_CALL_USERS_SUCCESS'
export const FETCH_BATCH_VIDEO_CALL_USERS_FAILURE = 'FETCH_BATCH_VIDEO_CALL_USERS_FAILURE'

export const FETCH_TOKEN_BY_USER = 'FETCH_TOKEN_BY_USER'
export const FETCH_TOKEN_BY_USER_SUCCESS = 'FETCH_TOKEN_BY_USER_SUCCESS'
export const FETCH_TOKEN_BY_USER_FAILURE = 'FETCH_TOKEN_BY_USER_FAILURE'

export const EDIT_SCHEDULE_MEETING_DETAILS = 'EDIT_SCHEDULE_MEETING_DETAILS'

export const IS_OPEN_TASK_TYPE_MODAL = "IS_OPEN_TASK_TYPE_MODAL"

export const SELECTED_LINKEDIN_COMMUNITY_ITEM = "SELECTED_LINKEDIN_COMMUNITY_ITEM"

export const PAGE_TASK_TITLE = 'PAGE_TASK_TITLE'
export const SETTING_MINIMUM_SPEND_MINUTES = 'SETTING_MINIMUM_SPEND_MINUTES'


export const SETTING_TASK_PAGE_AND_META_ID = 'SETTING_TASK_PAGE_AND_META_ID'

export const FETCH_GET_PAGES = "FETCH_GET_PAGES";
export const FETCH_GET_PAGES_SUCCESS = "FETCH_GET_PAGES_SUCCESS";
export const FETCH_GET_PAGES_FAILURE = "FETCH_GET_PAGES_FAILURE";
export const SETTING_TASK_META_ID = 'SETTING_TASK_META_ID'
export const SETTING_TASK_PAGE_ID = 'SETTING_TASK_PAGE_ID'

export const SELECTED_COMMUNITY_ITEM = "SELECTED_COMMUNITY_ITEM"

export const POST_PAGE_SECTION = "POST_PAGE_SECTION";
export const POST_PAGE_SECTION_SUCCESS = "POST_PAGE_SECTION_SUCCESS";
export const POST_PAGE_SECTION_FAILURE = "POST_PAGE_SECTION_FAILURE";


export const POST_UPDATE_USER_ONLINE_ACTIVITY_LOG = "POST_UPDATE_USER_ONLINE_ACTIVITY_LOG";
export const POST_UPDATE_USER_ONLINE_ACTIVITY_LOG_SUCCESS = "POST_UPDATE_USER_ONLINE_ACTIVITY_LOG_SUCCESS";
export const POST_UPDATE_USER_ONLINE_ACTIVITY_LOG_FAILURE = "POST_UPDATE_USER_ONLINE_ACTIVITY_LOG_FAILURE";




/**
 * Student.............................................................................................................................
 */

export const FETCH_STUDENT_COURSES = "FETCH_STUDENT_COURSES";
export const FETCH_STUDENT_COURSES_SUCCESS = "FETCH_STUDENT_COURSES_SUCCESS";
export const FETCH_STUDENT_COURSES_FAILURE = "FETCH_STUDENT_COURSES_FAILURE";

export const FETCH_STUDENT_COURSE_SECTION = "FETCH_STUDENT_COURSE_SECTION";
export const FETCH_STUDENT_COURSE_SECTION_SUCCESS = "FETCH_STUDENT_COURSE_SECTION_SUCCESS";
export const FETCH_STUDENT_COURSE_SECTION_FAILURE = "FETCH_STUDENT_COURSE_SECTION_FAILURE";

export const FETCH_STUDENT_COURSE_TOPICS = "FETCH_STUDENT_COURSE_TOPICS";
export const FETCH_STUDENT_COURSE_TOPICS_SUCCESS = "FETCH_STUDENT_COURSE_TOPICS_SUCCESS";
export const FETCH_STUDENT_COURSE_TOPICS_FAILURE = "FETCH_STUDENT_COURSE_TOPICS_FAILURE";

export const FETCH_STUDENT_COURSE_TASKS = "FETCH_STUDENT_COURSE_TASKS";
export const FETCH_STUDENT_COURSE_TASKS_SUCCESS = "FETCH_STUDENT_COURSE_TASKS_SUCCESS";
export const FETCH_STUDENT_COURSE_TASKS_FAILURE = "FETCH_STUDENT_COURSE_TASKS_FAILURE";

export const FETCH_STUDENT_COURSE_TASKS_DETAILS = "FETCH_STUDENT_COURSE_TASKS_DETAILS";
export const FETCH_STUDENT_COURSE_TASKS_DETAILS_SUCCESS = "FETCH_STUDENT_COURSE_TASKS_DETAILS_SUCCESS";
export const FETCH_STUDENT_COURSE_TASKS_DETAILS_FAILURE = "FETCH_STUDENT_COURSE_TASKS_DETAILS_FAILURE";


export const FETCH_FACULTIES_DETAILS = "FETCH_FACULTIES_DETAILS";
export const FETCH_FACULTIES_DETAILS_SUCCESS = "FETCH_FACULTIES_DETAILS_SUCCESS";
export const FETCH_FACULTIES_DETAILS_FAILURE = "FETCH_FACULTIES_DETAILS_FAILURE";

export const SETTING_DEFAULT_COURSE = "SETTING_DEFAULT_COURSE"

export const FETCH_ALL_BRANCHES_LIST = "FETCH_ALL_BRANCHES_LIST";
export const FETCH_ALL_BRANCHES_LIST_SUCCESS = "FETCH_ALL_BRANCHES_LIST_SUCCESS";
export const FETCH_ALL_BRANCHES_LIST_FAILURE = "FETCH_ALL_BRANCHES_LIST_FAILURE";


export const GET_TASK_DETAILS = "GET_TASK_DETAILS"

export const POST_STUDENT_COURSE_TASK_DETAILS = "POST_STUDENT_COURSE_TASK_DETAILS";
export const POST_STUDENT_COURSE_TASK_DETAILS_SUCCESS = "POST_STUDENT_COURSE_TASK_DETAILS_SUCCESS";
export const POST_STUDENT_COURSE_TASK_DETAILS_FAILURE = "POST_STUDENT_COURSE_TASK_DETAILS_FAILURE";

export const ADD_STUDENT_COURSE_TASK_RESPONSE_ID = "ADD_STUDENT_COURSE_TASK_RESPONSE_ID";

export const STUDENT_WRITTEN_QUESTION = "STUDENT_WRITTEN_QUESTION"

export const STUDENT_PROCEDURE_DATA = "STUDENT_PROCEDURE_DATA"

export const STUDENT_FLOW_DIAGRAM = "STUDENT_FLOW_DIAGRAM"

export const STUDENT_FLOW_DIAGRAM_IMAGE = 'STUDENT_FLOW_DIAGRAM_IMAGE'

export const STUDENT_PROGRAM_DATA = "STUDENT_PROGRAM_DATA"

export const STUDENT_CURRENT_COURSE_SECTION = "STUDENT_CURRENT_COURSE_SECTION"

export const IS_EXPAND_CODE_EDITOR = "IS_EXPAND_CODE_EDITOR"

export const IS_ACTIVE_SECTION = "IS_ACTIVE_SECTION"

export const STUDENT_CODE_SUBMISSION = "STUDENT_CODE_SUBMISSION"
export const STUDENT_CODE_SUBMISSION_SUCCESS = "STUDENT_CODE_SUBMISSION_SUCCESS"
export const STUDENT_CODE_SUBMISSION_FAILURE = "STUDENT_CODE_SUBMISSION_FAILURE"

export const SET_GUEST_SAMPLE_INPUT_OUTPUT_DATA = "SET_GUEST_SAMPLE_INPUT_OUTPUT_DATA"
export const SET_GUEST_RULES_DATA = "SET_GUEST_RULES_DATA"
export const SET_GUEST_PROCEDURE_DATA = "SET_GUEST_PROCEDURE_DATA"


/**
 * group chat
 */

export const POST_BATCH_CHAT = "POST_BATCH_CHAT"
export const POST_BATCH_CHAT_SUCCESS = "POST_BATCH_CHAT_SUCCESS"
export const POST_BATCH_CHAT_FAILURE = "POST_BATCH_CHAT_FAILURE"

export const FETCH_BATCH_CHAT = "FETCH_BATCH_CHAT"
export const FETCH_BATCH_CHAT_SUCCESS = "FETCH_BATCH_CHAT_SUCCESS"
export const FETCH_BATCH_CHAT_FAILURE = "FETCH_BATCH_CHAT_FAILURE"

export const FETCH_BATCH_USER_ONLINE_ACTIVITY_LOG = "FETCH_BATCH_USER_ONLINE_ACTIVITY_LOG"
export const FETCH_BATCH_USER_ONLINE_ACTIVITY_LOG_SUCCESS = "FETCH_BATCH_USER_ONLINE_ACTIVITY_LOG_SUCCESS"
export const FETCH_BATCH_USER_ONLINE_ACTIVITY_LOG_FAILURE = "FETCH_BATCH_USER_ONLINE_ACTIVITY_LOG_FAILURE"


//courseTopicsParentData

export const COURSE_TOPIC_PARENT_DATA = "COURSE_TOPIC_PARENT_DATA"
export const COURSE_TOPIC_PARENT_CHILD_DATA = "COURSE_TOPIC_PARENT_CHILD_DATA"



/**
 * student page section
 */

export const FETCH_STUDENT_PAGE_SECTIONS = 'FETCH_STUDENT_PAGE_SECTIONS'
export const FETCH_STUDENT_PAGE_SECTIONS_SUCCESS = 'FETCH_STUDENT_PAGE_SECTIONS_SUCCESS'
export const FETCH_STUDENT_PAGE_SECTIONS_FAILURE = 'FETCH_STUDENT_PAGE_SECTIONS_FAILURE'

export const FETCH_STUDENT_SECTION_TYPE_TITLE = 'FETCH_STUDENT_SECTION_TYPE_TITLE'
export const FETCH_STUDENT_SECTION_TYPE_TITLE_SUCCESS = 'FETCH_STUDENT_SECTION_TYPE_TITLE_SUCCESS'
export const FETCH_STUDENT_SECTION_TYPE_TITLE_FAILURE = 'FETCH_STUDENT_SECTION_TYPE_TITLE_FAILURE'

export const FETCH_STUDENT_SECTION_TYPE_IMAGE = 'FETCH_STUDENT_SECTION_TYPE_IMAGE'
export const FETCH_STUDENT_SECTION_TYPE_IMAGE_SUCCESS = 'FETCH_STUDENT_SECTION_TYPE_IMAGE_SUCCESS'
export const FETCH_STUDENT_SECTION_TYPE_IMAGE_FAILURE = 'FETCH_STUDENT_SECTION_TYPE_IMAGE_FAILURE'

export const FETCH_STUDENT_SECTION_TYPE_VIDEO = 'FETCH_STUDENT_SECTION_TYPE_VIDEO'
export const FETCH_STUDENT_SECTION_TYPE_VIDEO_SUCCESS = 'FETCH_STUDENT_SECTION_TYPE_VIDEO_SUCCESS'
export const FETCH_STUDENT_SECTION_TYPE_VIDEO_FAILURE = 'FETCH_STUDENT_SECTION_TYPE_VIDEO_FAILURE'

export const FETCH_STUDENT_SECTION_TYPE_PARAGRAPH = 'FETCH_STUDENT_SECTION_TYPE_PARAGRAPH'
export const FETCH_STUDENT_SECTION_TYPE_PARAGRAPH_SUCCESS = 'FETCH_STUDENT_SECTION_TYPE_PARAGRAPH_SUCCESS'
export const FETCH_STUDENT_SECTION_TYPE_PARAGRAPH_FAILURE = 'FETCH_STUDENT_SECTION_TYPE_PARAGRAPH_FAILURE'

export const FETCH_STUDENT_SECTION_TYPE_LIST = 'FETCH_STUDENT_SECTION_TYPE_LIST'
export const FETCH_STUDENT_SECTION_TYPE_LIST_SUCCESS = 'FETCH_STUDENT_SECTION_TYPE_LIST_SUCCESS'
export const FETCH_STUDENT_SECTION_TYPE_LIST_FAILURE = 'FETCH_STUDENT_SECTION_TYPE_LIST_FAILURE'

export const FETCH_STUDENT_SECTION_TYPE_MD = 'FETCH_STUDENT_SECTION_TYPE_MD'
export const FETCH_STUDENT_SECTION_TYPE_MD_SUCCESS = 'FETCH_STUDENT_SECTION_TYPE_MD_SUCCESS'
export const FETCH_STUDENT_SECTION_TYPE_MD_FAILURE = 'FETCH_STUDENT_SECTION_TYPE_MD_FAILURE'

export const FETCH_STUDENT_TASKS_TIMELINE = 'FETCH_STUDENT_TASKS_TIMELINE'
export const FETCH_STUDENT_TASKS_TIMELINE_SUCCESS = 'FETCH_STUDENT_TASKS_TIMELINE_SUCCESS'
export const FETCH_STUDENT_TASKS_TIMELINE_FAILURE = 'FETCH_STUDENT_TASKS_TIMELINE_FAILURE'

export const POST_TASK_BY_STUDENT = 'POST_TASK_BY_STUDENT'
export const POST_TASK_BY_STUDENT_SUCCESS = 'POST_TASK_BY_STUDENT_SUCCESS'
export const POST_TASK_BY_STUDENT_FAILURE = 'POST_TASK_BY_STUDENT_FAILURE'


export const TASK_TYPE = 'TASK_TYPE'

export const FETCH_STUDENT_TASKS_DETAILS_OPEN = 'FETCH_STUDENT_TASKS_DETAILS_OPEN'
export const FETCH_STUDENT_TASKS_DETAILS_OPEN_SUCCESS = 'FETCH_STUDENT_TASKS_DETAILS_OPEN_SUCCESS'
export const FETCH_STUDENT_TASKS_DETAILS_OPEN_FAILURE = 'FETCH_STUDENT_TASKS_DETAILS_OPEN_FAILURE'

export const COURSE_IDE_TYPE = 'COURSE_IDE_TYPE'


export const STUDENT_COURSE_SECTION_DATA_LIST = "STUDENT_COURSE_SECTION_DATA_LIST"

export const GET_MESSAGE_EVENTS = 'GET_MESSAGE_EVENTS'

export const POST_ADD_BATCH_COMPLETION_EVENT = 'POST_ADD_BATCH_COMPLETION_EVENT'
export const POST_ADD_BATCH_COMPLETION_EVENT_SUCCESS = 'POST_ADD_BATCH_COMPLETION_EVENT_SUCCESS'
export const POST_ADD_BATCH_COMPLETION_EVENT_FAILURE = 'POST_ADD_BATCH_COMPLETION_EVENT_FAILURE'

export const FETCH_GET_BATCH_COMPLETION_EVENT = 'FETCH_GET_BATCH_COMPLETION_EVENT'
export const FETCH_GET_BATCH_COMPLETION_EVENT_SUCCESS = 'FETCH_GET_BATCH_COMPLETION_EVENT_SUCCESS'
export const FETCH_GET_BATCH_COMPLETION_EVENT_FAILURE = 'FETCH_GET_BATCH_COMPLETION_EVENT_FAILURE'


