
export const CREATE_BROADCAST_MESSAGE = "CREATE_BROADCAST_MESSAGE";
export const CREATE_BROADCAST_MESSAGE_SUCCESS = "CREATE_BROADCAST_MESSAGE_SUCCESS";
export const CREATE_BROADCAST_MESSAGE_FAILURE = "CREATE_BROADCAST_MESSAGE_FAILURE";


export const FETCH_BROADCAST_MESSAGE = "FETCH_BROADCAST_MESSAGE";
export const FETCH_BROADCAST_MESSAGE_SUCCESS = "FETCH_BROADCAST_MESSAGE_SUCCESS";
export const FETCH_BROADCAST_MESSAGE_FAILURE = "FETCH_BROADCAST_MESSAGE_FAILURE";

export const FETCH_NOTIFICATIONS = "FETCH_NOTIFICATIONS"
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_FAILURE = "FETCH_NOTIFICATIONS_FAILURE";

export const IS_SHOW_BACK = "IS_SHOW_BACK"

export const NOTIFICATION_COUNT = 'NOTIFICATION_COUNT'

export const NOTIFICATION_COUNT_CLEAR = 'NOTIFICATION_COUNT_CLEAR'
