export const RESET_APP = 'RESET_APP'

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const USER_LOGIN_DETAILS = 'USER_LOGIN_DETAILS';

export const USER_DETAILS = 'USER_DETAILS'
export const SYNC_DETAILS = 'SYNC_DETAILS'

export const GET_APP_CONFIG_DATA = 'GET_APP_CONFIG_DATA'

export const WEB_APP_CONFIG = 'WEB_APP_CONFIG';
export const WEB_APP_CONFIG_SUCCESS = 'WEB_APP_CONFIG_SUCCESS';
export const WEB_APP_CONFIG_FAILURE = 'WEB_APP_CONFIG_FAILURE';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE';

export const GET_STUDENT_TASK_DATA = 'GET_STUDENT_TASK_DATA';

export const FCM_TOKEN = 'FCM_TOKEN'