export const VALIDATE_USER = "VALIDATE_USER";
export const VALIDATE_USER_SUCCESS = "VALIDATE_USER_SUCCESS";
export const VALIDATE_USER_FAIL = "VALIDATE_USER_FAIL";

export const VALIDATE_COMPANY_DETAILS = "VALIDATE_COMPANY_DETAILS";
export const VALIDATE_COMPANY_DETAILS_SUCCESS = "VALIDATE_COMPANY_DETAILS_SUCCESS";
export const VALIDATE_COMPANY_DETAILS_FAILURE = "VALIDATE_COMPANY_DETAILS_FAILURE";

export const REGISTER_ADMIN = "REGISTER_ADMIN";
export const REGISTER_ADMIN_SUCCESS = "REGISTER_ADMIN_SUCCESS";
export const REGISTER_ADMIN_FAILURE = "REGISTER_ADMIN_FAILURE";

export const UPLOAD_COMPANY_DOCUMENT = "UPLOAD_COMPANY_DOCUMENT";
export const UPLOAD_COMPANY_DOCUMENT_SUCCESS = "UPLOAD_COMPANY_DOCUMENT_SUCCESS";
export const UPLOAD_COMPANY_DOCUMENT_FAILURE = "UPLOAD_COMPANY_DOCUMENT_FAILURE";

export const OTP_LOGIN = "OTP_LOGIN";
export const OTP_LOGIN_SUCCESS = "OTP_LOGIN_SUCCESS";
export const OTP_LOGIN_FAILURE = "OTP_LOGIN_FAILURE";

export const RESEND_LOGIN_OTP = "RESEND_LOGIN_OTP";
export const RESEND_LOGIN_OTP_SUCCESS = "RESEND_LOGIN_OTP_SUCCESS";
export const RESEND_LOGIN_OTP_FAILURE = "RESEND_LOGIN_OTP_FAILURE";

export const ADMIN_VERIFICATION_OTP = "ADMIN_VERIFICATION_OTP";
export const ADMIN_VERIFICATION_OTP_SUCCESS = "ADMIN_VERIFICATION_OTP_SUCCESS";
export const ADMIN_VERIFICATION_OTP_FAILURE = "ADMIN_VERIFICATION_OTP_FAILURE";

export const NATURE_OF_BUSINESS = "NATURE_OF_BUSINESS";
export const NATURE_OF_BUSINESS_SUCCESS = "NATURE_OF_BUSINESS_SUCCESS";
export const NATURE_OF_BUSINESS_FAILURE = "NATURE_OF_BUSINESS_FAILURE";

export const TYPE_OF_BUSINESS = "TYPE_OF_BUSINESS";
export const TYPE_OF_BUSINESS_SUCCESS = "TYPE_OF_BUSINESS_SUCCESS";
export const TYPE_OF_BUSINESS_FAILURE = "TYPE_OF_BUSINESS_FAILURE";


export const UPDATE_ADMIN_DETAILS = 'UPDATE_ADMIN_DETAILS'

export const REGISTER_OTP_VERIFY = 'REGISTER_OTP_VERIFY'

export const UPDATE_COMPANY_DETAILS = 'UPDATE_COMPANY_DETAILS'


export const UPDATE_FILE_DETAILS = 'UPDATE_FILE_DETAILS'


export const RESET_REDUCER = "RESET_REDUCER";

export const POST_APP_CONFIG = "POST_APP_CONFIG";
export const POST_APP_CONFIG_SUCCESS = "POST_APP_CONFIG_SUCCESS";
export const POST_APP_CONFIG_FAILURE = "POST_APP_CONFIG_FAILURE";

export const GET_APP_CONFIG_DATA = "GET_APP_CONFIG_DATA"

export const GET_FCM_TOKEN = 'GET_FCM_TOKEN'

export const SET_ESSL_CONFIG = "SET_ESSL_CONFIG";
export const SET_ESSL_CONFIG_SUCCESS = "SET_ESSL_CONFIG_SUCCESS";
export const SET_ESSL_CONFIG_FAILURE = "SET_ESSL_CONFIG_FAILURE";

export const GET_ESSL_CONFIG = "GET_ESSL_CONFIG";
export const GET_ESSL_CONFIG_SUCCESS = "GET_ESSL_CONFIG_SUCCESS";
export const GET_ESSL_CONFIG_FAILURE = "GET_ESSL_CONFIG_FAILURE";


export const EDIT_ESSL_CONFIG_DETAILS = "EDIT_ESSL_CONFIG_DETAILS"
export const ADD_ESSL_DEVICE = "ADD_ESSL_DEVICE";
export const ADD_ESSL_DEVICE_SUCCESS = "ADD_ESSL_DEVICE_SUCCESS";
export const ADD_ESSL_DEVICE_FAILURE = "ADD_ESSL_DEVICE_FAILURE";

export const GET_ESSL_DEVICES = "GET_ESSL_DEVICES";
export const GET_ESSL_DEVICES_SUCCESS = "GET_ESSL_DEVICES_SUCCESS";
export const GET_ESSL_DEVICES_FAILURE = "GET_ESSL_DEVICES_FAILURE";

export const ESSL_DEVICE_DETAILS = "ESSL_DEVICE_DETAILS"

export const SYNC_ESSL_DEVICE_USERS = "SYNC_ESSL_DEVICE_USERS";
export const SYNC_ESSL_DEVICE_USERS_SUCCESS = "SYNC_ESSL_DEVICE_USERS_SUCCESS";
export const SYNC_ESSL_DEVICE_USERS_FAILURE = "SYNC_ESSL_DEVICE_USERS_FAILURE";

export const WEB_PUSH_REGISTER = "WEB_PUSH_REGISTER";
export const WEB_PUSH_REGISTER_SUCCESS = "WEB_PUSH_REGISTER_SUCCESS";
export const WEB_PUSH_REGISTER_FAILURE = "WEB_PUSH_REGISTER_FAILURE";

export const IS_WEB_PUSH_REGISTER = "IS_WEB_PUSH_REGISTER"
